using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using RoR2;
using UnityEngine;

// Original source table and RNG on an explicit two-item diagnostic Run list; no chest/grant.
public sealed partial class MovementBatchProbe {
 [Serializable] public class ChestDropTableReport {
  public bool sourceReady,catalogReady,weightsMatched,reproducible,distinctMatched,loopMatched,conserved,cleaned;
  public int[] allowed,sequence,repeat,otherSeed,distinct,loop,withoutLoop,histogram;
  public int pickupCount,sourceCount,cloneCount,instancesBefore,instancesAfter;public float[] sourceWeights,effectiveWeights;public uint moneyBefore,moneyAfter;public ulong xpBefore,xpAfter;
  public string scope,itemPrerequisites;
 }
 IEnumerator ProbeOriginalChestDropTable(CharacterBody player,Result cfg){
  r.chestDropTable=new ChestDropTableReport{scope="Original recovered dtChest1, BasicPickupDropTable/WeightedSelection/UniquePickup/Xoroshiro generation on explicit diagnostic base tier1 Syringe/tier2 ChainLightning Run lists. Source weights/replacement policy unchanged; absent tier3/other domains are explicit. No chest/purchase/drop physics/item grant/full Run availability/progression/platform entitlement acceptance."};r.phase="original-chest-drop-table";Save();
  Check(r.inputBarrel.cleaned&&Run.instance&&PickupCatalog.pickupCount==0&&!ownsPickupCatalog,"Accepted input barrel/empty pickup catalog required");
  var first=RoR2Content.Items.Syringe;var second=RoR2Content.Items.ChainLightning;var replacement=DLC1Content.Items.RandomlyLunar;
  r.chestDropTable.itemPrerequisites="first="+first.name+"|tier="+first.tier+"|locked="+Run.instance.IsItemExpansionLocked(first.itemIndex)+"|second="+second.name+"|tier="+second.tier+"|locked="+Run.instance.IsItemExpansionLocked(second.itemIndex)+"|replacement="+replacement.name+"|locked="+Run.instance.IsItemExpansionLocked(replacement.itemIndex)+"|stacks="+Util.GetItemCountGlobal(replacement.itemIndex,false,false);Save();
  Check(first&&second&&replacement&&first.tier==ItemTier.Tier1&&second.tier==ItemTier.Tier2&&!first.requiredExpansion&&!second.requiredExpansion&&!first.unlockableDef&&!second.unlockableDef&&!Run.instance.IsItemExpansionLocked(first.itemIndex)&&!Run.instance.IsItemExpansionLocked(second.itemIndex)&&Run.instance.IsItemExpansionLocked(replacement.itemIndex)&&Util.GetItemCountGlobal(replacement.itemIndex,false,false)==0,"Original allowed-base/ungranted locked replacement contract changed");
  var lists=new[]{Run.instance.availableTier1DropList,Run.instance.availableTier2DropList,Run.instance.availableTier3DropList,Run.instance.availableBossDropList,Run.instance.availableLunarItemDropList,Run.instance.availableLunarEquipmentDropList,Run.instance.availableLunarCombinedDropList,Run.instance.availableEquipmentDropList,Run.instance.availableVoidTier1DropList,Run.instance.availableVoidTier2DropList,Run.instance.availableVoidTier3DropList,Run.instance.availableVoidBossDropList,Run.instance.availableFoodTierDropList,Run.instance.availablePowerShapeItemsDropList};var saved=lists.Select(x=>x.ToArray()).ToArray();Check(lists.All(x=>x.Count==0),"Unowned Run drop domain present");
  var flags=BindingFlags.Static|BindingFlags.NonPublic;foreach(var name in new[]{"entries","itemIndexToPickupIndex","equipmentIndexToPickupIndex","artifactIndexToPickupIndex","miscPickupIndexToPickupIndex","droneIndexToPickupIndex","<pickupCount>k__BackingField"}){var field=typeof(PickupCatalog).GetField(name,flags);Check(field!=null,"Original pickup field missing: "+name);priorPickupFields[field]=field.GetValue(null);}
  pickupNameMap=(IDictionary)typeof(PickupCatalog).GetField("nameToPickupIndex",flags).GetValue(null);pickupTierMap=(IDictionary)typeof(PickupCatalog).GetField("itemTierToPickupIndex",flags).GetValue(null);Check(pickupNameMap.Count==0&&pickupTierMap.Count==0,"Unowned pickup maps");priorPickupAvailability=PickupCatalog.availability;ownsPickupCatalog=true;
  BasicPickupDropTable source=null,clone=null;var instances=(List<PickupDropTable>)RewardField(typeof(PickupDropTable),"instancesList").GetValue(null);int firstCount=player.inventory.GetItemCountPermanent(first),secondCount=player.inventory.GetItemCountPermanent(second);r.chestDropTable.moneyBefore=player.master.money;r.chestDropTable.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);
  try{
   PickupCatalog.SetEntries(ItemCatalog.allItemDefs.Select(x=>x.CreatePickupDef()).ToArray());r.chestDropTable.allowed=new[]{PickupCatalog.FindPickupIndex(first.itemIndex).value,PickupCatalog.FindPickupIndex(second.itemIndex).value};r.chestDropTable.pickupCount=PickupCatalog.pickupCount;
   r.chestDropTable.catalogReady=r.chestDropTable.allowed.Distinct().Count()==2&&r.chestDropTable.allowed.All(x=>PickupCatalog.GetPickupDef(new PickupIndex(x))!=null);Check(r.chestDropTable.catalogReady,"Original drop pickup identities missing");
   source=artifactBundle.LoadAsset<BasicPickupDropTable>(cfg.chestDropTableAsset);Check(source&&source.name=="dtChest1","Original chest drop asset missing");r.chestDropTable.sourceWeights=new[]{source.tier1Weight,source.tier2Weight,source.tier3Weight,source.bossWeight,source.lunarEquipmentWeight,source.lunarItemWeight,source.lunarCombinedWeight,source.equipmentWeight,source.voidTier1Weight,source.voidTier2Weight,source.voidTier3Weight,source.voidBossWeight,source.foodTierWeight,source.powerShapesWeight};r.chestDropTable.weightsMatched=r.chestDropTable.sourceWeights.SequenceEqual(new[]{.8f,.2f,.01f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f});r.chestDropTable.sourceCount=source.GetPickupCount();r.chestDropTable.instancesBefore=instances.Count;r.chestDropTable.sourceReady=r.chestDropTable.weightsMatched&&source.canDropBeReplaced&&source.requiredItemTags.Length==0&&source.bannedItemTags.Length==0&&source.GetPickupCount()==0&&instances.Contains(source);Check(r.chestDropTable.sourceReady,"Original chest table policy/empty source contract changed");
   clone=Instantiate(source);Check(instances.Contains(clone)&&instances.Count==r.chestDropTable.instancesBefore+1,"Original drop table OnEnable registration failed");lists[0].Add(new PickupIndex(r.chestDropTable.allowed[0]));lists[1].Add(new PickupIndex(r.chestDropTable.allowed[1]));clone.RegenerateDropTable(Run.instance);r.chestDropTable.cloneCount=clone.GetPickupCount();Check(r.chestDropTable.cloneCount==2,"Original drop table did not build two choices");var selection=(WeightedSelection<UniquePickup>)typeof(BasicPickupDropTable).GetField("selector",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(clone);r.chestDropTable.effectiveWeights=new[]{selection.GetChoice(0).weight,selection.GetChoice(1).weight};Check(r.chestDropTable.effectiveWeights.SequenceEqual(new[]{.8f,.2f})&&selection.GetChoice(0).value.pickupIndex.value==r.chestDropTable.allowed[0]&&selection.GetChoice(1).value.pickupIndex.value==r.chestDropTable.allowed[1],"Original weighted source domain differs");
   Func<ulong,int[]> sample=seed=>{var rng=new Xoroshiro128Plus(seed);var values=new int[64];for(int i=0;i<values.Length;i++){var pickup=clone.GeneratePickup(rng);Check(pickup.isValid&&!pickup.isTempItem&&r.chestDropTable.allowed.Contains(pickup.pickupIndex.value),"Original table emitted an unavailable/temporary pickup");values[i]=pickup.pickupIndex.value;}return values;};
   r.chestDropTable.sequence=sample(123456789UL);r.chestDropTable.repeat=sample(123456789UL);r.chestDropTable.otherSeed=sample(987654321UL);r.chestDropTable.histogram=r.chestDropTable.allowed.Select(x=>r.chestDropTable.sequence.Count(y=>y==x)).ToArray();r.chestDropTable.reproducible=r.chestDropTable.sequence.SequenceEqual(r.chestDropTable.repeat)&&!r.chestDropTable.sequence.SequenceEqual(r.chestDropTable.otherSeed)&&r.chestDropTable.histogram.All(x=>x>0);Check(r.chestDropTable.reproducible,"Original seeded choice sequence/domain differs");
   var distinct=new List<UniquePickup>();clone.GenerateDistinctPickups(distinct,2,new Xoroshiro128Plus(42UL),false);r.chestDropTable.distinct=distinct.Select(x=>x.pickupIndex.value).ToArray();r.chestDropTable.distinctMatched=r.chestDropTable.distinct.Distinct().Count()==2&&r.chestDropTable.distinct.OrderBy(x=>x).SequenceEqual(r.chestDropTable.allowed.OrderBy(x=>x));Check(r.chestDropTable.distinctMatched,"Original distinct selection failed");
   var loop=new List<UniquePickup>();var withoutLoop=new List<UniquePickup>();clone.GenerateDistinctPickups(loop,5,new Xoroshiro128Plus(42UL),true);clone.GenerateDistinctPickups(withoutLoop,5,new Xoroshiro128Plus(42UL),false);r.chestDropTable.loop=loop.Select(x=>x.pickupIndex.value).ToArray();r.chestDropTable.withoutLoop=withoutLoop.Select(x=>x.pickupIndex.value).ToArray();r.chestDropTable.loopMatched=loop.Count==5&&withoutLoop.Count==2&&loop.All(x=>r.chestDropTable.allowed.Contains(x.pickupIndex.value))&&r.chestDropTable.withoutLoop.Distinct().Count()==2;Check(r.chestDropTable.loopMatched,"Original loop/no-loop size semantics differ");
   r.chestDropTable.moneyAfter=player.master.money;r.chestDropTable.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);r.chestDropTable.conserved=r.chestDropTable.moneyBefore==r.chestDropTable.moneyAfter&&r.chestDropTable.xpBefore==r.chestDropTable.xpAfter&&firstCount==player.inventory.GetItemCountPermanent(first)&&secondCount==player.inventory.GetItemCountPermanent(second)&&Util.GetItemCountGlobal(replacement.itemIndex,false,false)==0;Check(r.chestDropTable.conserved,"Original loot generation changed inventory/funds/XP or granted replacement item");Save();
  }finally{for(int i=0;i<lists.Length;i++){lists[i].Clear();lists[i].AddRange(saved[i]);}if(clone)Destroy(clone);CleanupOriginalItemPickup();}
  yield return null;yield return null;r.chestDropTable.instancesAfter=instances.Count;r.chestDropTable.cleaned=!clone&&!ownsPickupCatalog&&PickupCatalog.pickupCount==0&&pickupNameMap.Count==0&&pickupTierMap.Count==0&&lists.Select((x,i)=>x.SequenceEqual(saved[i])).All(x=>x)&&instances.Count==r.chestDropTable.instancesBefore&&instances.Contains(source)&&source.GetPickupCount()==r.chestDropTable.sourceCount;Check(r.chestDropTable.cleaned,"Owned table/catalog/drop-domain cleanup incomplete");Save();
 }
}
