using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using RoR2;
using UnityEngine;
using UnityEngine.Networking;

// Observes source purchase callbacks and states; original payment/roll/input implementations remain intact.
public sealed partial class MovementBatchProbe {
 [Serializable] public class ChestPurchaseReport {
  public bool sourceReady,callbacks,rolled,secondaryUnavailable,selected,unaffordableRejected,paid,opening,opened,repeatRejected,selectionReleased,conserved,cleaned;
  public int cost,pickup,dropCount,interactions,detailedPurchases,globalPurchases,renderers,colliders,tableBefore,tableAfter;public uint moneyBefore,funding,moneyFunded,moneyAfter,netId;public ulong xpBefore,xpAfter;
  public float openingSeconds;public string[] callbackMethods;public string state,statsContext,scope;
 }
 BuffDef[] ChestPurchaseBuffs(Result cfg){if(!cfg.originalChestPurchase)return new BuffDef[0];var def=artifactBundle.LoadAsset<BuffDef>(cfg.freeUnlockBuffAsset);Check(def&&def.name=="bdFreeUnlocks","Original purchase buff missing");BindEnemyDefinition(typeof(DLC2Content.Buffs),"FreeUnlocks",def);return new[]{def};}
 ArtifactDef[] ChestPurchaseArtifacts(Result cfg){if(!cfg.originalChestPurchase)return new ArtifactDef[0];var def=artifactBundle.LoadAsset<ArtifactDef>(cfg.delusionArtifactAsset);Check(def&&def.cachedName=="Delusion","Original Delusion comparison missing");BindEnemyDefinition(typeof(CU8Content.Artifacts),"Delusion",def);return new[]{def};}
 IEnumerator ProbeOriginalChestPurchase(CharacterBody player,Result cfg){
  r.chestPurchase=new ChestPurchaseReport{scope="Original Chest1 natural lifecycle/roll, source serialized callbacks, input/server Money25 purchase and Opening/Opened. Diagnostic funding/placement/materials/two-item Run lists. Animator disabled, owned SfxLocator omitted; no ejection/physics/grant/visual opening/native audio/normal placement/profile/startup acceptance."};var report=r.chestPurchase;r.phase="original-chest-purchase-prepare";Save();
  Check(r.chestDropTable.cleaned&&r.inputBarrel.cleaned&&Run.instance&&NetworkServer.active&&activeBodyClient.isConnected&&player.networkIdentity.hasAuthority&&!PauseStopController.instance,"Accepted chest/input/local ownership required");
  var driver=player.GetComponent<InteractionDriver>();var bank=player.inputBank;var priorAim=bank.aimDirection;float priorScale=Time.timeScale;Check(!driver.enabled&&!driver.currentInteractable&&!bank.interact.down,"Original neutral interaction required");
  Check(DLC2Content.Buffs.FreeUnlocks&&player.GetBuffCount(DLC2Content.Buffs.FreeUnlocks)==0&&DLC2Content.Items.LowerPricedChestsConsumed&&player.inventory.GetItemCountPermanent(DLC2Content.Items.LowerPricedChests)==0&&player.inventory.GetItemCountPermanent(DLC2Content.Items.LowerPricedChestsConsumed)==0&&Run.instance.IsItemExpansionLocked(DLC2Content.Items.LowerPricedChests.itemIndex)&&Run.instance.IsItemExpansionLocked(DLC2Content.Items.LowerPricedChestsConsumed.itemIndex)&&!DelusionChestController.isDelusionEnable,"Original free/sale/Delusion branches must remain unavailable");
  report.moneyBefore=player.master.money;report.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);Check(report.moneyBefore==8,"Accepted barrel wallet changed");var syringe=player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe);var lightning=player.inventory.GetItemCountPermanent(RoR2Content.Items.ChainLightning);
  var stats=RoR2.Stats.PlayerStatsComponent.FindBodyStatSheet(player);report.statsContext=stats==null?"Original inactive master has no stat sheet; original StatManager returns naturally, no profile/stat acceptance.":"Original existing stat sheet retained; no profile persistence acceptance.";
  var lists=new[]{Run.instance.availableTier1DropList,Run.instance.availableTier2DropList};var saved=lists.Select(x=>x.ToArray()).ToArray();Check(lists.All(x=>x.Count==0)&&PickupCatalog.pickupCount==0&&!ownsPickupCatalog,"Unowned drop/catalog context present");
  var flags=BindingFlags.Static|BindingFlags.NonPublic;foreach(var name in new[]{"entries","itemIndexToPickupIndex","equipmentIndexToPickupIndex","artifactIndexToPickupIndex","miscPickupIndexToPickupIndex","droneIndexToPickupIndex","<pickupCount>k__BackingField"}){var field=typeof(PickupCatalog).GetField(name,flags);Check(field!=null,"Original pickup field missing "+name);priorPickupFields[field]=field.GetValue(null);}pickupNameMap=(IDictionary)typeof(PickupCatalog).GetField("nameToPickupIndex",flags).GetValue(null);pickupTierMap=(IDictionary)typeof(PickupCatalog).GetField("itemTierToPickupIndex",flags).GetValue(null);Check(pickupNameMap.Count==0&&pickupTierMap.Count==0,"Unowned pickup maps");priorPickupAvailability=PickupCatalog.availability;ownsPickupCatalog=true;
  moneyCatalogField=typeof(CostTypeCatalog).GetField("costTypeDefs",flags);priorMoneyCatalog=moneyCatalogField.GetValue(null);Check(priorMoneyCatalog==null&&!ownsMoneyCatalog,"Unowned money catalog");ownsMoneyCatalog=true;
  GameObject staging=null,chestObject=null,pauseHost=null;Transform model=null;ChestBehavior chest=null;PurchaseInteraction purchase=null;BasicPickupDropTable table=null;var materials=new List<Material>();var requesters=(HashSet<UnityEngine.Object>)typeof(OutlineHighlight).GetField("preRenderHighlightRequesters",flags).GetValue(null);int priorRequesters=requesters.Count;
  Action<Interactor,IInteractable,GameObject> interaction=(actor,component,obj)=>{if(obj!=chestObject)return;Check(actor==driver.interactor&&ReferenceEquals(component,purchase),"Original chest input event differs");report.interactions++;};
  Action<CostTypeDef.PayCostContext,CostTypeDef.PayCostResults> detailed=(context,result)=>{Check(context.activator==driver.interactor&&context.activatorBody==player&&context.activatorMaster==player.master&&context.activatorInventory==player.inventory&&context.purchasedObject==chestObject&&context.purchaseInteraction==purchase&&context.cost==25&&context.costTypeDef==CostTypeCatalog.GetCostTypeDef(CostTypeIndex.Money)&&context.rng!=null&&result.itemStacksTaken.Count==0&&result.equipmentTaken.Count==0,"Original detailed purchase context differs");report.detailedPurchases++;};
  Action<CostTypeDef.PayCostContext,CostTypeDef.PayCostResults> global=(context,result)=>{if(context.purchasedObject==chestObject){Check(context.purchaseInteraction==purchase&&context.activatorBody==player,"Original global purchase identity differs");report.globalPurchases++;}};
  try{
   StaticCall(typeof(CostTypeCatalog),"Init");Check(CostTypeCatalog.costTypeCount==16&&CostTypeCatalog.GetCostTypeDef(CostTypeIndex.Money).name=="Money","Original cost catalog changed");PickupCatalog.SetEntries(ItemCatalog.allItemDefs.Select(x=>x.CreatePickupDef()).ToArray());lists[0].Add(PickupCatalog.FindPickupIndex(RoR2Content.Items.Syringe.itemIndex));lists[1].Add(PickupCatalog.FindPickupIndex(RoR2Content.Items.ChainLightning.itemIndex));
   var source=artifactBundle.LoadAsset<GameObject>(cfg.chestAsset);table=artifactBundle.LoadAsset<BasicPickupDropTable>(cfg.chestDropTableAsset);Check(source&&source.name=="Chest1"&&table&&source.GetComponentsInChildren<Component>(true).All(x=>x),"Original chest prefab/reference missing");report.tableBefore=table.GetPickupCount();Check(report.tableBefore==0,"Original source table cache not empty");table.RegenerateDropTable(Run.instance);Check(table.GetPickupCount()==2,"Original source chest table domain differs");
   staging=new GameObject("Owned inactive chest staging");staging.SetActive(false);chestObject=Instantiate(source,staging.transform);chestObject.name=source.name;chest=chestObject.GetComponent<ChestBehavior>();purchase=chestObject.GetComponent<PurchaseInteraction>();var machine=chestObject.GetComponent<EntityStateMachine>();var locator=chestObject.GetComponent<ModelLocator>();var picker=chestObject.GetComponent<PickupPickerController>();var prompt=chestObject.GetComponent<NetworkUIPromptController>();var delusion=chestObject.GetComponent<DelusionChestController>();Check(chest&&purchase&&machine&&locator&&picker&&prompt&&delusion,"Original chest components missing");model=locator.modelTransform;Check(model,"Original chest model missing");
   report.cost=purchase.cost;report.sourceReady=chest.dropTable==table&&!chest.dropTransform&&chest.minDropCount==1&&chest.maxDropCount==1&&chest.dropUpVelocityStrength==20&&chest.dropForwardVelocityStrength==2&&chest.openState.stateType==typeof(EntityStates.Barrel.Opening)&&purchase.cost==25&&purchase.costType==CostTypeIndex.Money&&purchase.available&&!purchase.automaticallyScaleCostWithDifficulty&&string.IsNullOrEmpty(purchase.requiredUnlockable)&&!purchase.requiredExpansion&&purchase.saleStarCompatible&&purchase.purchaseStatNames.Length==0&&!chest.isCommandChest&&!chest.isChestReset;Check(report.sourceReady,"Original source chest policy changed");
   report.callbackMethods=Enumerable.Range(0,purchase.onPurchase.GetPersistentEventCount()).Select(purchase.onPurchase.GetPersistentMethodName).ToArray();report.callbacks=report.callbackMethods.SequenceEqual(new[]{"SetAvailable","Open"})&&purchase.onPurchase.GetPersistentTarget(0)==purchase&&purchase.onPurchase.GetPersistentTarget(1)==chest;Check(report.callbacks,"Original serialized purchase callbacks unresolved");
   var allowed=new[]{typeof(NetworkIdentity),typeof(NetworkStateMachine),typeof(EntityStateMachine),typeof(ChestBehavior),typeof(PurchaseInteraction),typeof(DelusionChestController),typeof(ModelLocator),typeof(EntityLocator),typeof(ChildLocator),typeof(PingInfoProvider)};foreach(var behaviour in chestObject.GetComponentsInChildren<MonoBehaviour>(true))behaviour.enabled=allowed.Contains(behaviour.GetType());foreach(var animator in chestObject.GetComponentsInChildren<Animator>(true))animator.enabled=false;var sound=chestObject.GetComponent<SfxLocator>();Check(sound,"Original source chest SfxLocator missing");DestroyImmediate(sound);
   var shader=Resources.Load<Shader>("StageSurfacePreview");Check(shader&&shader.isSupported,"Accepted source-view shader missing");foreach(var renderer in chestObject.GetComponentsInChildren<Renderer>(true)){renderer.sharedMaterials=renderer.sharedMaterials.Select(original=>{Check(original,"Original source chest material missing");var copy=new Material(original);copy.shader=shader;materials.Add(copy);return copy;}).ToArray();report.renderers++;if(renderer is SkinnedMeshRenderer skinned){var view=new GameObject("Owned chest renderer view");view.layer=30;view.transform.SetParent(renderer.transform,false);var copy=view.AddComponent<SkinnedMeshRenderer>();copy.sharedMesh=skinned.sharedMesh;copy.sharedMaterials=renderer.sharedMaterials;copy.bones=skinned.bones;copy.rootBone=skinned.rootBone;copy.localBounds=skinned.localBounds;copy.updateWhenOffscreen=true;}}
   foreach(var collider in chestObject.GetComponentsInChildren<Collider>(true)){collider.enabled=true;report.colliders++;}Check(report.renderers>0&&report.colliders>0,"Original source chest geometry missing");chestObject.transform.position=player.characterMotor.Motor.TransientPosition+Vector3.right*2;chestObject.transform.SetParent(null,true);chestObject.SetActive(true);NetworkServer.Spawn(chestObject);Physics.SyncTransforms();yield return null;yield return null;Call(activeBodyClient,"Update");
   report.netId=chestObject.GetComponent<NetworkIdentity>().netId.Value;report.pickup=chest.currentPickup.pickupIndex.value;report.dropCount=chest.dropCount;report.rolled=report.netId!=0&&machine.state is EntityStates.Idle&&chest.dropTransform==chestObject.transform&&chest.dropTable==table&&chest.currentPickup.isValid&&!chest.currentPickup.isTempItem&&(chest.currentPickup.pickupIndex==lists[0][0]||chest.currentPickup.pickupIndex==lists[1][0])&&chest.dropCount==1;Check(report.rolled,"Original natural chest Awake/Start/roll failed");report.secondaryUnavailable=!delusion.enabled&&!picker.enabled&&!prompt.enabled&&picker.GetInteractability(driver.interactor)==Interactability.Disabled&&delusion.delusionChest==chest;Check(report.secondaryUnavailable,"Original natural inactive Delusion/secondary path failed");
   pauseHost=new GameObject("Owned original chest pause context");pauseHost.SetActive(false);pauseHost.AddComponent<NetworkIdentity>();var pause=pauseHost.AddComponent<PauseStopController>();pauseHost.SetActive(true);yield return null;yield return null;Call(activeBodyClient,"Update");Check(PauseStopController.instance==pause&&!pause.isPaused&&Time.timeScale==priorScale,"Original chest pause context differs");
   var target=model.GetComponentsInChildren<Collider>(true).First(x=>x.enabled);bank.aimDirection=(target.bounds.center-bank.aimOrigin).normalized;driver.enabled=true;float deadline=Time.realtimeSinceStartup+3;while(driver.currentInteractable!=chestObject&&Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");}report.selected=driver.currentInteractable==chestObject&&requesters.Contains(driver);Check(report.selected&&purchase.GetInteractability(driver.interactor)==Interactability.ConditionsNotMet&&!CameraRigController.IsObjectSpectatedByAnyCamera(player.gameObject),"Original unaffordable target/rpc-sound guard differs");
   GlobalEventManager.OnInteractionsGlobal+=interaction;purchase.onDetailedPurchaseServer.AddListener((context,result)=>detailed(context,result));PurchaseInteraction.onPurchaseGlobalServer+=global;
   bank.interact.PushState(true);yield return new WaitForFixedUpdate();yield return new WaitForEndOfFrame();bank.interact.PushState(false);yield return null;bank.interact.PushState(false);Call(activeBodyClient,"Update");report.unaffordableRejected=player.master.money==report.moneyBefore&&report.interactions==0&&report.detailedPurchases==0&&report.globalPurchases==0&&purchase.available&&machine.state is EntityStates.Idle;Check(report.unaffordableRejected,"Unaffordable source chest dispatched purchase");
   report.funding=(uint)report.cost-report.moneyBefore;player.master.GiveMoney(report.funding);report.moneyFunded=player.master.money;Check(report.moneyFunded==25&&purchase.GetInteractability(driver.interactor)==Interactability.Available,"Original funded chest affordability failed");float began=Time.realtimeSinceStartup;bank.interact.PushState(true);r.phase="original-chest-opening";Save();yield return new WaitForFixedUpdate();yield return new WaitForEndOfFrame();bank.interact.PushState(false);bank.interact.PushState(false);deadline=began+4;while(Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");report.state=machine.state.GetType().FullName;report.opening|=machine.state is EntityStates.Barrel.Opening;if(machine.state is EntityStates.Barrel.Opened){report.opened=true;report.openingSeconds=Time.realtimeSinceStartup-began;break;}Save();}
   report.moneyAfter=player.master.money;report.paid=report.interactions==1&&report.detailedPurchases==1&&report.globalPurchases==1&&report.moneyAfter==0&&!purchase.available&&purchase.lastActivator==driver.interactor;Check(report.paid&&report.opening&&report.opened&&report.openingSeconds>=EntityStates.Barrel.Opening.duration&&report.openingSeconds<2,"Original source chest payment/callback/opening failed");
   bank.interact.PushState(true);yield return new WaitForFixedUpdate();yield return new WaitForEndOfFrame();bank.interact.PushState(false);yield return null;bank.interact.PushState(false);report.repeatRejected=player.master.money==0&&report.interactions==1&&report.detailedPurchases==1&&report.globalPurchases==1&&purchase.GetInteractability(driver.interactor)==Interactability.Disabled;Check(report.repeatRejected,"Original unavailable chest paid twice");report.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);report.conserved=report.xpBefore==report.xpAfter&&player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)==syringe&&player.inventory.GetItemCountPermanent(RoR2Content.Items.ChainLightning)==lightning&&player.inventory.GetItemCountPermanent(DLC2Content.Items.LowerPricedChestsConsumed)==0&&chest.currentPickup.pickupIndex.value==report.pickup&&chest.dropCount==1&&!chest.NetworkisChestOpened;Check(report.conserved,"Purchase ejected/granted loot or changed XP/inventory");
   foreach(var collider in chestObject.GetComponentsInChildren<Collider>(true).Concat(model.GetComponentsInChildren<Collider>(true)).Distinct())collider.enabled=false;Physics.SyncTransforms();deadline=Time.realtimeSinceStartup+2;while(driver.currentInteractable&&Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");}report.selectionReleased=chestObject&&!driver.currentInteractable&&!requesters.Contains(driver);Check(report.selectionReleased,"Original chest selection retained after withdrawal");Save();
  }finally{GlobalEventManager.OnInteractionsGlobal-=interaction;PurchaseInteraction.onPurchaseGlobalServer-=global;driver.enabled=false;bank.interact.PushState(false);bank.interact.PushState(false);bank.aimDirection=priorAim;if(chestObject)NetworkServer.Destroy(chestObject);if(staging)Destroy(staging);if(pauseHost)NetworkServer.Destroy(pauseHost);foreach(var material in materials)if(material)Destroy(material);for(int i=0;i<lists.Length;i++){lists[i].Clear();lists[i].AddRange(saved[i]);}if(table)table.RegenerateDropTable(Run.instance);CleanupOriginalMoneyCost();CleanupOriginalItemPickup();}
  yield return null;yield return null;Call(activeBodyClient,"Update");report.tableAfter=table.GetPickupCount();report.cleaned=!chestObject&&!model&&!staging&&!pauseHost&&!PauseStopController.instance&&materials.All(x=>!x)&&!driver.enabled&&!driver.currentInteractable&&!bank.interact.down&&requesters.Count==priorRequesters&&!requesters.Contains(driver)&&!ownsMoneyCatalog&&ReferenceEquals(moneyCatalogField.GetValue(null),priorMoneyCatalog)&&!ownsPickupCatalog&&PickupCatalog.pickupCount==0&&pickupNameMap.Count==0&&pickupTierMap.Count==0&&lists.Select((x,i)=>x.SequenceEqual(saved[i])).All(x=>x)&&report.tableAfter==report.tableBefore&&Time.timeScale==priorScale;Check(report.cleaned,"Original chest/model/material/input/pause/table/catalog cleanup failed");Save();
 }
}
