using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using RoR2;
using RoR2.Audio;
using UnityEngine;
using UnityEngine.Networking;

public sealed class ClientCoinReturnObservation : MonoBehaviour {
 public bool disabled;public float fixedAtDisable,wallAtDisable;
 void OnDisable(){disabled=true;fixedAtDisable=Time.fixedTime;wallAtDisable=Time.realtimeSinceStartup;}
}

// Observes the original message handler, effect factory, coin Start and pooled timer.
public sealed partial class MovementBatchProbe {
 [Serializable] public class ClientCoinReport {
  public bool originalDefaultInitialized,sourceReady,handlerRegistered,received,spawned,burstsMatched,naturallyReturned,conserved,cleaned;
  public int messages,requestedCount,originalCount,effectIndex,budgetBefore,budgetAfter,poolCount,particlePeak;public int[] tierValues,burstCounts;public string factoryObservation;public string[] factoryInstances,burstModes;public float[] burstConstants,burstMinimums,burstMaximums,burstTimes;
  public uint moneyBefore,moneyAfter;public ulong xpBefore,xpAfter;public float duration,seconds,peakAge,fixedSeconds,lastFixedSeconds;public int fixedTicks,inUseAfter;public bool returnedActive;public string scope,mediumBefore,mediumDeclared,mediumActive,mediumRestored;
 }
 IEnumerator ProbeOriginalClientCoin(CharacterBody player){
  r.clientCoin=new ClientCoinReport{requestedCount=683,scope="Original transmitted message52/client effect factory, recovered CoinEmitter/CoinBehavior tier bursts and natural pooled timer return. Cosmetic diagnostic count683 does not grant money. One owned original VFX budget default is explicitly initialized/restored; full Console initialization is unproven. No interaction press/reward linkage/physical input/native audio/particle material parity or startup acceptance."};r.phase="original-client-coin-prepare";Save();
  Check(activeBodyClient!=null&&activeBodyClient.isConnected&&player.networkIdentity.hasAuthority&&NetworkServer.active&&r.interactionSelection.cleaned,"Accepted original selection/local client required");
  var prefab=rewardPrefabs[0];var source=prefab.GetComponent<CoinBehavior>();var sourceEffect=prefab.GetComponent<EffectComponent>();var sourceTimer=prefab.GetComponent<DestroyOnTimer>();var sourceVfx=prefab.GetComponent<VFXAttributes>();
  var pools=(Dictionary<GameObject,EffectPool>)RewardField(typeof(EffectManager),"_EffectPrefabMap").GetValue(null);var cache=(Dictionary<GameObject,bool>)RewardField(typeof(EffectManager),"_ShouldUsePooledEffectMap").GetValue(null);
  var baseline=Resources.FindObjectsOfTypeAll<CoinBehavior>().Where(x=>x.gameObject.scene.IsValid()).ToArray();Check(baseline.Length==0&&!pools.ContainsKey(prefab)&&!cache.ContainsKey(prefab)&&!activeBodyClient.handlers.ContainsKey(52),"Unowned coin instances/pool/cache/message handler");
  r.clientCoin.duration=sourceTimer.duration;r.clientCoin.tierValues=source.coinTiers.Select(x=>x.valuePerCoin).ToArray();r.clientCoin.budgetBefore=VFXBudget.totalCost;
  var data=new EffectData{origin=player.corePosition+Vector3.right*2,genericFloat=r.clientCoin.requestedCount};var effectIndex=EffectCatalog.FindEffectIndexFromPrefab(prefab);r.clientCoin.effectIndex=(int)effectIndex;
  r.clientCoin.sourceReady=sourceEffect&&sourceTimer.duration==3&&sourceVfx&&!sourceVfx.DoNotPool&&sourceVfx.vfxPriority==VFXAttributes.VFXPriority.Medium&&r.clientCoin.tierValues.SequenceEqual(new[]{500,150,25,5,1})&&string.IsNullOrEmpty(sourceEffect.soundName)&&data.surfaceDefIndex==SurfaceDefIndex.Invalid&&data.networkSoundEventIndex==NetworkSoundEventIndex.Invalid&&effectIndex!=EffectIndex.Invalid&&EffectManager.UsePools&&!EffectManager.DisableAllEffectSpawning&&VFXBudget.totalCost+sourceVfx.GetIntensityScore()<200;
  Check(r.clientCoin.sourceReady,"Original silent coin source/catalog/default budget contract changed");
  r.clientCoin.moneyBefore=player.master.money;r.clientCoin.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);CoinBehavior clone=null;EffectPool ownedPool=null;
  var medium=(RoR2.ConVar.IntConVar)RewardField(typeof(VFXBudget),"mediumPriorityCostThreshold").GetValue(null);r.clientCoin.mediumBefore=medium.GetString();r.clientCoin.mediumDeclared=medium.defaultValue;Check(r.clientCoin.mediumBefore=="0"&&r.clientCoin.mediumDeclared=="200","Original skipped budget/default contract changed");
  var original=(NetworkMessageDelegate)Delegate.CreateDelegate(typeof(NetworkMessageDelegate),typeof(EffectManager).GetMethod("HandleEffectClient",BindingFlags.NonPublic|BindingFlags.Static));
  try{
   medium.AttemptSetString(medium.defaultValue);r.clientCoin.mediumActive=medium.GetString();r.clientCoin.originalDefaultInitialized=r.clientCoin.mediumActive==r.clientCoin.mediumDeclared;Check(r.clientCoin.originalDefaultInitialized,"Original VFX default setter failed");
   activeBodyClient.RegisterHandler(52,msg=>{r.clientCoin.messages++;original(msg);var incoming=RewardField(typeof(EffectManager),"incomingEffectMessage").GetValue(null);var incomingType=incoming.GetType();var received=(EffectData)incomingType.GetField("effectData").GetValue(incoming);r.clientCoin.received=(EffectIndex)incomingType.GetField("effectIndex").GetValue(incoming)==effectIndex&&received.genericFloat==data.genericFloat&&Vector3.Distance(received.origin,data.origin)<.001f&&received.surfaceDefIndex==SurfaceDefIndex.Invalid&&received.networkSoundEventIndex==NetworkSoundEventIndex.Invalid;Check(r.clientCoin.received,"Original coin message decode mismatch");});r.clientCoin.handlerRegistered=activeBodyClient.handlers.ContainsKey(52);
   float began=Time.realtimeSinceStartup,fixedBegan=Time.fixedTime;int tickBegan=r.runClock.fixedTicks;EffectManager.SpawnEffect(prefab,data,true);Call(activeBodyClient,"Update");yield return null;yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");
   var allCoins=Resources.FindObjectsOfTypeAll<CoinBehavior>();var created=allCoins.Where(x=>x.gameObject.scene.IsValid()&&!baseline.Contains(x)).ToArray();var definition=EffectCatalog.GetEffectDef(effectIndex);r.clientCoin.factoryInstances=allCoins.Select(x=>x.name+"|scene="+x.gameObject.scene.IsValid()+"|active="+x.gameObject.activeInHierarchy+"|count="+x.originalCoinCount).ToArray();r.clientCoin.factoryObservation="created="+created.Length+"|definition="+(definition!=null&&definition.prefab==prefab)+"|cull="+(definition!=null&&definition.cullMethod!=null)+"|budget="+VFXBudget.totalCost+"|realCost="+VFXBudget.realTotalCost+"|mediumThreshold="+((RoR2.ConVar.IntConVar)RewardField(typeof(VFXBudget),"mediumPriorityCostThreshold").GetValue(null)).GetString()+"|pool="+pools.ContainsKey(prefab)+"|cache="+cache.ContainsKey(prefab)+"|client="+NetworkClient.active+"|disabled="+EffectManager.DisableAllEffectSpawning;Save();Check(r.clientCoin.messages==1&&r.clientCoin.received&&created.Length==1,"Original message/factory did not create one coin effect");clone=created[0];Check(pools.TryGetValue(prefab,out ownedPool),"Original coin pool missing");
   var actual=clone.GetComponent<EffectComponent>();var helper=clone.GetComponent<EffectManagerHelper>();var timer=clone.GetComponent<DestroyOnTimer>();var returned=clone.gameObject.AddComponent<ClientCoinReturnObservation>();r.clientCoin.originalCount=clone.originalCoinCount;
   r.clientCoin.spawned=clone.gameObject.activeInHierarchy&&clone.originalCoinCount==r.clientCoin.requestedCount&&actual.effectIndex==effectIndex&&actual.effectData.genericFloat==data.genericFloat&&Vector3.Distance(clone.transform.position,data.origin)<.001f&&helper&&helper.OwningPool==ownedPool&&ownedPool.InUseCount()==1&&timer.enabled&&timer.duration==sourceTimer.duration;Check(r.clientCoin.spawned,"Original coin Start/data/pool/timer identity mismatch");
   var expected=new[]{1,1,1,1,3};r.clientCoin.burstCounts=new int[expected.Length];r.clientCoin.burstModes=new string[expected.Length];r.clientCoin.burstConstants=new float[expected.Length];r.clientCoin.burstMinimums=new float[expected.Length];r.clientCoin.burstMaximums=new float[expected.Length];r.clientCoin.burstTimes=new float[expected.Length];for(int i=0;i<expected.Length;i++){var tier=clone.coinTiers[i];var emission=tier.particleSystem.emission;Check(tier.valuePerCoin==r.clientCoin.tierValues[i]&&emission.enabled&&emission.burstCount==1&&tier.particleSystem.gameObject.activeInHierarchy,"Original coin tier emission missing");var burst=emission.GetBurst(0);r.clientCoin.burstModes[i]=burst.count.mode.ToString();r.clientCoin.burstConstants[i]=burst.count.constant;r.clientCoin.burstMinimums[i]=burst.count.constantMin;r.clientCoin.burstMaximums[i]=burst.count.constantMax;r.clientCoin.burstTimes[i]=burst.time;r.clientCoin.burstCounts[i]=(int)burst.count.constant;Check(burst.time==0&&burst.count.mode==ParticleSystemCurveMode.Constant&&burst.count.constant==expected[i],"Original coin tier burst differs");}r.clientCoin.burstsMatched=r.clientCoin.burstCounts.SequenceEqual(expected);r.phase="original-client-coin-active";Save();
   float deadline=began+5;while(clone.gameObject.activeInHierarchy&&Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");r.clientCoin.peakAge=Mathf.Max(r.clientCoin.peakAge,timer.GetAge());r.clientCoin.particlePeak=Math.Max(r.clientCoin.particlePeak,clone.GetComponentsInChildren<ParticleSystem>(true).Sum(x=>x.particleCount));if(Time.frameCount%10==0)Save();}
   r.clientCoin.seconds=returned.wallAtDisable-began;r.clientCoin.fixedSeconds=returned.fixedAtDisable-fixedBegan;r.clientCoin.lastFixedSeconds=Time.fixedTime-fixedBegan;r.clientCoin.fixedTicks=r.runClock.fixedTicks-tickBegan;r.clientCoin.inUseAfter=ownedPool.InUseCount();r.clientCoin.returnedActive=clone.gameObject.activeInHierarchy;r.clientCoin.poolCount=ownedPool.PoolCount();r.clientCoin.naturallyReturned=returned.disabled&&clone&&!clone.gameObject.activeInHierarchy&&ownedPool.InUseCount()==0&&ownedPool.PoolCount()==1&&r.clientCoin.fixedSeconds>=sourceTimer.duration&&r.clientCoin.fixedSeconds<sourceTimer.duration+.05f&&Mathf.Abs(r.clientCoin.lastFixedSeconds-r.clientCoin.fixedTicks*Time.fixedDeltaTime)<.01f&&r.clientCoin.lastFixedSeconds>=r.clientCoin.fixedSeconds&&Mathf.Abs(r.clientCoin.seconds-r.clientCoin.fixedSeconds)<.3f&&r.clientCoin.peakAge>=sourceTimer.duration-.1f;Check(r.clientCoin.naturallyReturned,"Original coin timer did not naturally return pooled effect");
   r.clientCoin.moneyAfter=player.master.money;r.clientCoin.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);r.clientCoin.budgetAfter=VFXBudget.totalCost;r.clientCoin.conserved=r.clientCoin.messages==1&&r.clientCoin.moneyAfter==r.clientCoin.moneyBefore&&r.clientCoin.xpAfter==r.clientCoin.xpBefore&&r.clientCoin.budgetAfter==r.clientCoin.budgetBefore&&player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)==1;Check(r.clientCoin.conserved,"Cosmetic coin effect changed funds/XP/item/budget");
  }finally{
   activeBodyClient.UnregisterHandler(52);if(pools.TryGetValue(prefab,out ownedPool)){foreach(var inUse in ownedPool.InUse.ToArray())ownedPool.ReturnObject(inUse);EffectManager.ClearPool(prefab);ownedPool.Kill();}cache.Remove(prefab);medium.AttemptSetString(r.clientCoin.mediumBefore);r.clientCoin.mediumRestored=medium.GetString();
  }
  yield return null;yield return null;r.clientCoin.cleaned=r.clientCoin.mediumRestored==r.clientCoin.mediumBefore&&medium.defaultValue==r.clientCoin.mediumDeclared&&!activeBodyClient.handlers.ContainsKey(52)&&!pools.ContainsKey(prefab)&&!cache.ContainsKey(prefab)&&!clone&&Resources.FindObjectsOfTypeAll<CoinBehavior>().Count(x=>x.gameObject.scene.IsValid())==baseline.Length&&VFXBudget.totalCost==r.clientCoin.budgetBefore;Check(r.clientCoin.cleaned,"Owned coin handler/pool/cache/effect cleanup incomplete");Save();
 }
}
