using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using RoR2;
using RoR2.Audio;
using UnityEngine;
using UnityEngine.Networking;

public sealed class ClientCoinReturnObservation : MonoBehaviour {
 public bool disabled;public float fixedAtDisable,wallAtDisable;
 void OnDisable(){disabled=true;fixedAtDisable=Time.fixedTime;wallAtDisable=Time.realtimeSinceStartup;}
}

// Observes the original message handler, effect factory, coin Start and pooled timer.
public sealed partial class MovementBatchProbe {
 [Serializable] public class ClientCoinReport {
  public bool originalDefaultInitialized,sourceReady,handlerRegistered,received,spawned,burstsMatched,naturallyReturned,conserved,rewardsMatched,cleaned;
  public int messages,requestedCount,originalCount,effectIndex,budgetBefore,budgetAfter,poolCount,particlePeak;public int[] tierValues,burstCounts;public string factoryObservation;public string[] factoryInstances,burstModes;public float[] burstConstants,burstMinimums,burstMaximums,burstTimes;
  public uint moneyBefore,moneyAfter;public ulong xpBefore,xpAfter;public float duration,seconds,peakAge,fixedSeconds,lastFixedSeconds;public int fixedTicks,inUseAfter;public bool returnedActive;public string scope,mediumBefore,mediumDeclared,mediumActive,mediumRestored;
 }
 IEnumerator ProbeOriginalClientCoin(CharacterBody player,bool inputDriven=false){
  var coinReport=new ClientCoinReport{requestedCount=inputDriven?r.inputBarrel.source.goldExpected:683,scope="Original transmitted message52/client effect factory, recovered CoinEmitter/CoinBehavior tier bursts and natural pooled timer return. Cosmetic diagnostic count683 does not grant money. One owned original VFX budget default is explicitly initialized/restored; full Console initialization is unproven. No interaction press/reward linkage/physical input/native audio/particle material parity or startup acceptance."};if(inputDriven){r.inputBarrel.coin=coinReport;coinReport.scope="Original automatic InteractionDriver input/server barrel reward with original client coin handler/factory/timer; source reward count, no manual effect/wallet/XP calls. Original optional XP cosmetics unavailable, native audio/coin rendering/physical/full startup unproven.";}else r.clientCoin=coinReport;r.phase="original-client-coin-prepare";Save();
  Check(activeBodyClient!=null&&activeBodyClient.isConnected&&player.networkIdentity.hasAuthority&&NetworkServer.active&&r.interactionSelection.cleaned,"Accepted original selection/local client required");
  var prefab=rewardPrefabs[0];var source=prefab.GetComponent<CoinBehavior>();var sourceEffect=prefab.GetComponent<EffectComponent>();var sourceTimer=prefab.GetComponent<DestroyOnTimer>();var sourceVfx=prefab.GetComponent<VFXAttributes>();
  var pools=(Dictionary<GameObject,EffectPool>)RewardField(typeof(EffectManager),"_EffectPrefabMap").GetValue(null);var cache=(Dictionary<GameObject,bool>)RewardField(typeof(EffectManager),"_ShouldUsePooledEffectMap").GetValue(null);
  var baseline=Resources.FindObjectsOfTypeAll<CoinBehavior>().Where(x=>x.gameObject.scene.IsValid()).ToArray();Check(baseline.Length==0&&!pools.ContainsKey(prefab)&&!cache.ContainsKey(prefab)&&!activeBodyClient.handlers.ContainsKey(52),"Unowned coin instances/pool/cache/message handler");
  coinReport.duration=sourceTimer.duration;coinReport.tierValues=source.coinTiers.Select(x=>x.valuePerCoin).ToArray();coinReport.budgetBefore=VFXBudget.totalCost;
  var data=new EffectData{origin=inputDriven?barrelObject.transform.position:player.corePosition+Vector3.right*2,genericFloat=coinReport.requestedCount};var effectIndex=EffectCatalog.FindEffectIndexFromPrefab(prefab);coinReport.effectIndex=(int)effectIndex;
  coinReport.sourceReady=sourceEffect&&sourceTimer.duration==3&&sourceVfx&&!sourceVfx.DoNotPool&&sourceVfx.vfxPriority==VFXAttributes.VFXPriority.Medium&&coinReport.tierValues.SequenceEqual(new[]{500,150,25,5,1})&&string.IsNullOrEmpty(sourceEffect.soundName)&&data.surfaceDefIndex==SurfaceDefIndex.Invalid&&data.networkSoundEventIndex==NetworkSoundEventIndex.Invalid&&effectIndex!=EffectIndex.Invalid&&EffectManager.UsePools&&!EffectManager.DisableAllEffectSpawning&&VFXBudget.totalCost+sourceVfx.GetIntensityScore()<200;
  Check(coinReport.sourceReady,"Original silent coin source/catalog/default budget contract changed");
  coinReport.moneyBefore=player.master.money;coinReport.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);CoinBehavior clone=null;EffectPool ownedPool=null;
  var medium=(RoR2.ConVar.IntConVar)RewardField(typeof(VFXBudget),"mediumPriorityCostThreshold").GetValue(null);coinReport.mediumBefore=medium.GetString();coinReport.mediumDeclared=medium.defaultValue;Check(coinReport.mediumBefore=="0"&&coinReport.mediumDeclared=="200","Original skipped budget/default contract changed");
  var original=(NetworkMessageDelegate)Delegate.CreateDelegate(typeof(NetworkMessageDelegate),typeof(EffectManager).GetMethod("HandleEffectClient",BindingFlags.NonPublic|BindingFlags.Static));
  float factoryWall=0,factoryFixed=0;int factoryTick=0;
  try{
   medium.AttemptSetString(medium.defaultValue);coinReport.mediumActive=medium.GetString();coinReport.originalDefaultInitialized=coinReport.mediumActive==coinReport.mediumDeclared;Check(coinReport.originalDefaultInitialized,"Original VFX default setter failed");
   activeBodyClient.RegisterHandler(52,msg=>{coinReport.messages++;factoryWall=Time.realtimeSinceStartup;factoryFixed=Time.fixedTime;factoryTick=r.runClock.fixedTicks;original(msg);var incoming=RewardField(typeof(EffectManager),"incomingEffectMessage").GetValue(null);var incomingType=incoming.GetType();var received=(EffectData)incomingType.GetField("effectData").GetValue(incoming);coinReport.received=(EffectIndex)incomingType.GetField("effectIndex").GetValue(incoming)==effectIndex&&received.genericFloat==data.genericFloat&&Vector3.Distance(received.origin,data.origin)<.001f&&received.surfaceDefIndex==SurfaceDefIndex.Invalid&&received.networkSoundEventIndex==NetworkSoundEventIndex.Invalid;Check(coinReport.received,"Original coin message decode mismatch");});coinReport.handlerRegistered=activeBodyClient.handlers.ContainsKey(52);
   float began=Time.realtimeSinceStartup;if(inputDriven){player.inputBank.interact.PushState(true);r.inputBarrel.pressed=player.inputBank.interact.justPressed;Check(r.inputBarrel.pressed,"Original interaction press missing");yield return new WaitForFixedUpdate();yield return new WaitForEndOfFrame();player.inputBank.interact.PushState(false);r.inputBarrel.released=player.inputBank.interact.justReleased;Check(r.inputBarrel.released,"Original interaction release missing");}else EffectManager.SpawnEffect(prefab,data,true);Call(activeBodyClient,"Update");yield return null;yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");if(inputDriven)player.inputBank.interact.PushState(false);
   var allCoins=Resources.FindObjectsOfTypeAll<CoinBehavior>();var created=allCoins.Where(x=>x.gameObject.scene.IsValid()&&!baseline.Contains(x)).ToArray();var definition=EffectCatalog.GetEffectDef(effectIndex);coinReport.factoryInstances=allCoins.Select(x=>x.name+"|scene="+x.gameObject.scene.IsValid()+"|active="+x.gameObject.activeInHierarchy+"|count="+x.originalCoinCount).ToArray();coinReport.factoryObservation="created="+created.Length+"|definition="+(definition!=null&&definition.prefab==prefab)+"|cull="+(definition!=null&&definition.cullMethod!=null)+"|budget="+VFXBudget.totalCost+"|realCost="+VFXBudget.realTotalCost+"|mediumThreshold="+((RoR2.ConVar.IntConVar)RewardField(typeof(VFXBudget),"mediumPriorityCostThreshold").GetValue(null)).GetString()+"|pool="+pools.ContainsKey(prefab)+"|cache="+cache.ContainsKey(prefab)+"|client="+NetworkClient.active+"|disabled="+EffectManager.DisableAllEffectSpawning;Save();Check(coinReport.messages==1&&coinReport.received&&created.Length==1,"Original message/factory did not create one coin effect");clone=created[0];Check(pools.TryGetValue(prefab,out ownedPool),"Original coin pool missing");
   var actual=clone.GetComponent<EffectComponent>();var helper=clone.GetComponent<EffectManagerHelper>();var timer=clone.GetComponent<DestroyOnTimer>();var returned=clone.gameObject.AddComponent<ClientCoinReturnObservation>();coinReport.originalCount=clone.originalCoinCount;
   coinReport.spawned=clone.gameObject.activeInHierarchy&&clone.originalCoinCount==coinReport.requestedCount&&actual.effectIndex==effectIndex&&actual.effectData.genericFloat==data.genericFloat&&Vector3.Distance(clone.transform.position,data.origin)<.001f&&helper&&helper.OwningPool==ownedPool&&ownedPool.InUseCount()==1&&timer.enabled&&timer.duration==sourceTimer.duration;Check(coinReport.spawned,"Original coin Start/data/pool/timer identity mismatch");
   var expected=inputDriven?new[]{0,0,0,coinReport.requestedCount/5,coinReport.requestedCount%5}:new[]{1,1,1,1,3};Check(!inputDriven||(coinReport.requestedCount>=5&&coinReport.requestedCount<25),"Measured barrel reward range changed");coinReport.burstCounts=new int[expected.Length];coinReport.burstModes=new string[expected.Length];coinReport.burstConstants=new float[expected.Length];coinReport.burstMinimums=new float[expected.Length];coinReport.burstMaximums=new float[expected.Length];coinReport.burstTimes=new float[expected.Length];for(int i=0;i<expected.Length;i++){var tier=clone.coinTiers[i];var emission=tier.particleSystem.emission;Check(tier.valuePerCoin==coinReport.tierValues[i]&&emission.enabled&&emission.burstCount==1&&(expected[i]==0?!tier.particleSystem.gameObject.activeSelf:tier.particleSystem.gameObject.activeInHierarchy),"Original coin tier emission missing");var burst=emission.GetBurst(0);coinReport.burstModes[i]=burst.count.mode.ToString();coinReport.burstConstants[i]=burst.count.constant;coinReport.burstMinimums[i]=burst.count.constantMin;coinReport.burstMaximums[i]=burst.count.constantMax;coinReport.burstTimes[i]=burst.time;coinReport.burstCounts[i]=expected[i]==0?0:(int)burst.count.constant;Check(expected[i]==0||(burst.time==0&&burst.count.mode==ParticleSystemCurveMode.Constant&&burst.count.constant==expected[i]),"Original coin tier burst differs");}coinReport.burstsMatched=coinReport.burstCounts.SequenceEqual(expected);r.phase=inputDriven?"original-input-barrel-coin":"original-client-coin-active";Save();
   float deadline=began+5;while(clone.gameObject.activeInHierarchy&&Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");if(inputDriven){r.inputBarrel.opening|=barrelMachine.state is EntityStates.Barrel.Opening;r.inputBarrel.opened|=barrelMachine.state is EntityStates.Barrel.Opened;}coinReport.peakAge=Mathf.Max(coinReport.peakAge,timer.GetAge());coinReport.particlePeak=Math.Max(coinReport.particlePeak,clone.GetComponentsInChildren<ParticleSystem>(true).Sum(x=>x.particleCount));if(Time.frameCount%10==0)Save();}
   coinReport.seconds=returned.wallAtDisable-factoryWall;coinReport.fixedSeconds=returned.fixedAtDisable-factoryFixed;coinReport.lastFixedSeconds=Time.fixedTime-factoryFixed;coinReport.fixedTicks=r.runClock.fixedTicks-factoryTick;coinReport.inUseAfter=ownedPool.InUseCount();coinReport.returnedActive=clone.gameObject.activeInHierarchy;coinReport.poolCount=ownedPool.PoolCount();coinReport.naturallyReturned=returned.disabled&&clone&&!clone.gameObject.activeInHierarchy&&ownedPool.InUseCount()==0&&ownedPool.PoolCount()==1&&coinReport.fixedSeconds>=sourceTimer.duration&&coinReport.fixedSeconds<sourceTimer.duration+.05f&&Mathf.Abs(coinReport.lastFixedSeconds-coinReport.fixedTicks*Time.fixedDeltaTime)<.01f&&coinReport.lastFixedSeconds>=coinReport.fixedSeconds&&Mathf.Abs(coinReport.seconds-coinReport.fixedSeconds)<.3f&&coinReport.peakAge>=sourceTimer.duration-.1f;Check(coinReport.naturallyReturned,"Original coin timer did not naturally return pooled effect");
   coinReport.moneyAfter=player.master.money;coinReport.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);coinReport.budgetAfter=VFXBudget.totalCost;coinReport.conserved=coinReport.messages==1&&coinReport.moneyAfter==coinReport.moneyBefore&&coinReport.xpAfter==coinReport.xpBefore&&coinReport.budgetAfter==coinReport.budgetBefore&&player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)==1;if(inputDriven){coinReport.rewardsMatched=coinReport.messages==1&&coinReport.moneyAfter-coinReport.moneyBefore==r.inputBarrel.source.goldExpected&&coinReport.xpAfter-coinReport.xpBefore==r.inputBarrel.source.experienceExpected&&coinReport.budgetAfter==coinReport.budgetBefore&&player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)==1;Check(coinReport.rewardsMatched,"Original input reward/coin budget result differs");}else Check(coinReport.conserved,"Cosmetic coin effect changed funds/XP/item/budget");
  }finally{
   activeBodyClient.UnregisterHandler(52);if(pools.TryGetValue(prefab,out ownedPool)){foreach(var inUse in ownedPool.InUse.ToArray())ownedPool.ReturnObject(inUse);EffectManager.ClearPool(prefab);ownedPool.Kill();}cache.Remove(prefab);medium.AttemptSetString(coinReport.mediumBefore);coinReport.mediumRestored=medium.GetString();
  }
  yield return null;yield return null;coinReport.cleaned=coinReport.mediumRestored==coinReport.mediumBefore&&medium.defaultValue==coinReport.mediumDeclared&&!activeBodyClient.handlers.ContainsKey(52)&&!pools.ContainsKey(prefab)&&!cache.ContainsKey(prefab)&&!clone&&Resources.FindObjectsOfTypeAll<CoinBehavior>().Count(x=>x.gameObject.scene.IsValid())==baseline.Length&&VFXBudget.totalCost==coinReport.budgetBefore;Check(coinReport.cleaned,"Owned coin handler/pool/cache/effect cleanup incomplete");Save();
 }
}
