using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using RoR2;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.AddressableAssets;
using UnityEngine.AddressableAssets.ResourceLocators;
using UnityEngine.ResourceManagement.AsyncOperations;
using UnityEngine.ResourceManagement.ResourceLocations;
using UnityEngine.ResourceManagement.ResourceProviders;

public sealed partial class MovementBatchProbe {
 [Serializable] public class DefaultPickupReport {
  public bool syncLoaded,asyncMatched,callbackMatched,pendingBalanced,sourceMatched,factory,modelCreated,modelMoving,earlyDisabled,available,conserved,objectCleaned,leasesCleaned;
  public int referencesBefore,referencesAfter,locatorsBefore,locatorsAfter,pendingBefore,pendingAfter,vertices,renderers,instancesBefore,instancesAfter;public uint netId,moneyBefore,moneyAfter;public ulong xpBefore,xpAfter;
  public float waitSeconds,modelScale,spinDegrees;public string modelName,scope;
 }
 GameObject defaultPickupSource;ResourceLocationMap defaultPickupLocator;AsyncOperationHandle<GameObject> defaultPickupHandle;FieldInfo defaultPickupField;object previousDefaultPickup;bool ownsDefaultSync,ownsDefaultAsync,ownsDefaultInit;
 GameObject GenericPickupSource(Result cfg){return cfg.originalDefaultPickup?defaultPickupSource:artifactBundle.LoadAsset<GameObject>(cfg.pickupAsset);}
 IEnumerator PrepareOriginalDefaultPickup(Result cfg){
  r.defaultPickup=new DefaultPickupReport{scope="Original sync/async/GenericPickup Init/default factory with original active PickupDisplay and direct Syringe model; diagnostic placement/material/view layer. No prefab override/display omission/manual simulation/item grant/chest ejection/native audio/full startup acceptance."};var report=r.defaultPickup;r.phase="original-default-pickup-load";Save();
  defaultPickupField=RewardField(typeof(GenericPickupController),"pickupPrefab");Check(defaultPickupField!=null&&defaultPickupField.GetValue(null)==null&&!defaultPickupSource&&defaultPickupLocator==null,"Unowned original generic prefab/lease present");previousDefaultPickup=defaultPickupField.GetValue(null);report.locatorsBefore=Addressables.ResourceLocators.Count();report.pendingBefore=LegacyResourcesAPI.ActiveCount;Check(report.pendingBefore==0&&!AssetBundle.GetAllLoadedAssetBundles().Any(x=>x.name=="generic-pickup-lab"),"Unowned generic request/bundle present");string key;Check(LegacyResourcesAPI.GetGuid("Prefabs/NetworkedObjects/GenericPickup",out key)&&key==cfg.genericPickupKey,"Original generic legacy identity changed");
  var bundle=new ResourceLocationBase("generic-pickup-lab",System.IO.Path.Combine(Application.persistentDataPath,"payload","generic-pickup-lab"),typeof(AssetBundleProvider).FullName,typeof(IAssetBundleResource));bundle.Data=new AssetBundleRequestOptions{BundleName="generic-pickup-lab"};defaultPickupLocator=new ResourceLocationMap("owned-default-generic-pickup");defaultPickupLocator.Add(key,new ResourceLocationBase(key,cfg.pickupAsset,typeof(BundledAssetProvider).FullName,typeof(GameObject),bundle));Addressables.AddResourceLocator(defaultPickupLocator);
  defaultPickupSource=LegacyResourcesAPI.Load<GameObject>("Prefabs/NetworkedObjects/GenericPickup");ownsDefaultSync=defaultPickupSource;report.syncLoaded=defaultPickupSource&&defaultPickupSource.name=="GenericPickup"&&!defaultPickupSource.scene.IsValid();Check(report.syncLoaded,"Original default generic sync source failed");defaultPickupHandle=LegacyResourcesAPI.LoadAsync<GameObject>("Prefabs/NetworkedObjects/GenericPickup");ownsDefaultAsync=true;yield return defaultPickupHandle;yield return null;report.asyncMatched=defaultPickupHandle.Status==AsyncOperationStatus.Succeeded&&defaultPickupHandle.Result==defaultPickupSource;Check(report.asyncMatched,"Original generic async source identity differs");
  var controller=defaultPickupSource.GetComponent<GenericPickupController>();report.sourceMatched=controller&&controller.pickupDisplay&&controller.pickupDisplay.enabled&&controller.waitDuration==.5f&&defaultPickupSource.GetComponentsInChildren<Component>(true).All(x=>x)&&defaultPickupSource.GetComponentsInChildren<MonoBehaviour>(true).All(x=>!x.GetType().Name.StartsWith("Ak",StringComparison.Ordinal));Check(report.sourceMatched,"Original full generic component/display source changed");Func<int> references=()=> (int)typeof(AsyncOperationHandle<GameObject>).GetProperty("ReferenceCount",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(defaultPickupHandle);report.referencesBefore=references();Check(report.referencesBefore==2,"Original generic source acquisitions differ");StaticCall(typeof(GenericPickupController),"Init");float deadline=Time.realtimeSinceStartup+8;while(defaultPickupField.GetValue(null)==null&&Time.realtimeSinceStartup<deadline)yield return null;yield return null;ownsDefaultInit=defaultPickupField.GetValue(null)!=null;report.referencesAfter=references();report.callbackMatched=ReferenceEquals(defaultPickupField.GetValue(null),defaultPickupSource)&&report.referencesAfter==report.referencesBefore+1;report.pendingAfter=LegacyResourcesAPI.ActiveCount;report.pendingBalanced=report.pendingAfter==report.pendingBefore;Check(report.callbackMatched&&report.pendingBalanced,"Original generic Init callback/refcount/pending failed");Save();
 }
 IEnumerator ProbeOriginalDefaultPickup(CharacterBody player,Result cfg){
  var report=r.defaultPickup;r.phase="original-default-pickup-factory";Save();Check(report.callbackMatched&&r.pickupDropletCollision.cleaned&&NetworkServer.active&&activeBodyClient.isConnected&&!ownsPickupCatalog&&PickupCatalog.pickupCount==0,"Accepted source/collision/local client context required");var item=RoR2Content.Items.Syringe;Check(item&&!item.requiredExpansion&&!item.unlockableDef&&item.pickupModelPrefab&&string.IsNullOrEmpty(item.pickupModelReference.RuntimeKey.ToString()),"Original allowed direct Syringe display changed");
  var flags=BindingFlags.Static|BindingFlags.NonPublic;foreach(var name in new[]{"entries","itemIndexToPickupIndex","equipmentIndexToPickupIndex","artifactIndexToPickupIndex","miscPickupIndexToPickupIndex","droneIndexToPickupIndex","<pickupCount>k__BackingField"}){var field=typeof(PickupCatalog).GetField(name,flags);Check(field!=null,"Original default pickup field missing "+name);priorPickupFields[field]=field.GetValue(null);}pickupNameMap=(IDictionary)typeof(PickupCatalog).GetField("nameToPickupIndex",flags).GetValue(null);pickupTierMap=(IDictionary)typeof(PickupCatalog).GetField("itemTierToPickupIndex",flags).GetValue(null);Check(pickupNameMap.Count==0&&pickupTierMap.Count==0,"Unowned default pickup maps");priorPickupAvailability=PickupCatalog.availability;ownsPickupCatalog=true;
  report.moneyBefore=player.master.money;report.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);int count=player.inventory.GetItemCountPermanent(item);var materials=new List<Material>();GameObject model=null;NetworkInstanceId id=default;Func<int> instances=()=>Resources.FindObjectsOfTypeAll<GenericPickupController>().Count(x=>x.gameObject.scene.IsValid()&&x.gameObject.activeInHierarchy);report.instancesBefore=instances();Check(report.instancesBefore==0,"Unowned live pickup before default factory");
  try{
   PickupCatalog.SetEntries(ItemCatalog.allItemDefs.Select(x=>x.CreatePickupDef()).ToArray());var index=PickupCatalog.FindPickupIndex(item.itemIndex);var def=PickupCatalog.GetPickupDef(index);Check(def!=null&&def.displayPrefab==item.pickupModelPrefab&&!Run.instance.IsItemExpansionLocked(item.itemIndex),"Original direct model pickup definition differs");var actor=player.characterMotor.Motor.TransientPosition;RaycastHit hit;Check(Physics.Raycast(actor+Vector3.right*6+Vector3.up*30,Vector3.down,out hit,100,LayerIndex.world.mask,QueryTriggerInteraction.Ignore)&&hit.collider.gameObject.scene==stageGeometryScene,"Original default pickup terrain absent");var info=new GenericPickupController.CreatePickupInfo{pickup=new UniquePickup{pickupIndex=index},position=hit.point+Vector3.up*2,rotation=Quaternion.identity};ownedPickup=GenericPickupController.CreatePickup(in info);Check(ownedPickup,"Original default factory returned no pickup");pickupObject=ownedPickup.gameObject;id=pickupObject.GetComponent<NetworkIdentity>().netId;report.netId=id.Value;report.factory=!info.prefabOverride&&pickupObject.name==defaultPickupSource.name+"(Clone)"&&ownedPickup.pickup==info.pickup&&ownedPickup.pickupDisplay&&ownedPickup.pickupDisplay.enabled&&!ownedPickup.Duplicated&&!ownedPickup.Recycled&&!ownedPickup.chestGeneratedFrom&&id.Value!=0&&NetworkServer.FindLocalObject(id)==pickupObject;Check(report.factory,"Original no-override default factory/state/display failed");yield return null;Call(activeBodyClient,"Update");Check(ClientScene.FindLocalObject(id)==pickupObject,"Original default pickup client mapping absent");
   var display=ownedPickup.pickupDisplay;model=(GameObject)typeof(PickupDisplay).GetField("modelObject",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(display);report.modelName=model?model.name:"missing";report.modelCreated=model&&model.name==item.pickupModelPrefab.name+"(Clone)"&&model.transform.parent==display.transform&&display.modelRenderer&&display.GetPickupIndex()==index;Check(report.modelCreated,"Original PickupDisplay did not create exact direct Syringe model");report.modelScale=model.transform.localScale.x;report.vertices=model.GetComponentsInChildren<MeshFilter>(true).Sum(x=>x.sharedMesh?x.sharedMesh.vertexCount:0);Check(report.modelScale>0&&report.vertices>50,"Original display scale/mesh missing");var shader=Resources.Load<Shader>("StageSurfacePreview");Check(shader&&shader.isSupported,"Accepted owned preview shader unavailable");foreach(var renderer in model.GetComponentsInChildren<Renderer>(true)){renderer.gameObject.layer=30;renderer.sharedMaterials=renderer.sharedMaterials.Select(original=>{Check(original,"Original model material missing");var copy=new Material(original);copy.shader=shader;materials.Add(copy);return copy;}).ToArray();report.renderers++;}Check(report.renderers>0,"Original Syringe renderer absent");
   var interactor=player.GetComponent<Interactor>();var stamp=(Run.FixedTimeStamp)typeof(GenericPickupController).GetField("waitStartTime",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(ownedPickup);report.earlyDisabled=ownedPickup.GetInteractability(interactor)==Interactability.Disabled&&stamp.timeSince<.5f;Check(report.earlyDisabled,"Original default Start/initial delay missing");float deadline=Time.realtimeSinceStartup+2;while(stamp.timeSince<.5f&&Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");Check(pickupObject&&player.inventory.GetItemCountPermanent(item)==count,"Default pickup granted during delay");}report.waitSeconds=stamp.timeSince;report.available=ownedPickup.GetInteractability(interactor)==Interactability.Available&&report.waitSeconds>=.5f&&report.waitSeconds<.7f;Check(report.available,"Original default half-second delay/permission failed");
   r.phase="original-default-pickup-visible";Save();var rotation=model.transform.localRotation;yield return new WaitForSeconds(2);report.spinDegrees=Quaternion.Angle(rotation,model.transform.localRotation);report.modelMoving=report.spinDegrees>20&&display.enabled&&pickupObject&&model;Check(report.modelMoving,"Original display automatic spin/lifetime absent");report.moneyAfter=player.master.money;report.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);report.conserved=report.moneyBefore==report.moneyAfter&&report.xpBefore==report.xpAfter&&player.inventory.GetItemCountPermanent(item)==count&&instances()==1;Check(report.conserved,"Original default pickup changed inventory/funds/XP or duplicated");Save();
  }finally{CleanupOriginalItemPickup();foreach(var material in materials)if(material)Destroy(material);}
  yield return null;yield return null;Call(activeBodyClient,"Update");report.instancesAfter=instances();report.objectCleaned=!pickupObject&&!model&&materials.All(x=>!x)&&!NetworkServer.FindLocalObject(id)&&!ClientScene.FindLocalObject(id)&&report.instancesAfter==report.instancesBefore&&!ownsPickupCatalog&&PickupCatalog.pickupCount==0&&pickupNameMap.Count==0&&pickupTierMap.Count==0;Check(report.objectCleaned,"Owned default pickup/model/material/catalog/maps retained");Save();
 }
 void CleanupOriginalDefaultPickup(){
  if(defaultPickupField==null&&defaultPickupLocator==null&&!ownsDefaultSync&&!ownsDefaultAsync&&!ownsDefaultInit)return;
  if(defaultPickupField!=null)defaultPickupField.SetValue(null,previousDefaultPickup);if(ownsDefaultInit&&defaultPickupSource)Addressables.Release(defaultPickupSource);if(ownsDefaultAsync&&defaultPickupHandle.IsValid())Addressables.Release(defaultPickupHandle);if(ownsDefaultSync&&defaultPickupSource)Addressables.Release(defaultPickupSource);if(defaultPickupLocator!=null)Addressables.RemoveResourceLocator(defaultPickupLocator);ownsDefaultInit=ownsDefaultAsync=ownsDefaultSync=false;defaultPickupSource=null;defaultPickupLocator=null;
  if(r.defaultPickup!=null){var report=r.defaultPickup;report.locatorsAfter=Addressables.ResourceLocators.Count();report.leasesCleaned=defaultPickupField!=null&&ReferenceEquals(defaultPickupField.GetValue(null),previousDefaultPickup)&&!defaultPickupHandle.IsValid()&&!AssetBundle.GetAllLoadedAssetBundles().Any(x=>x.name=="generic-pickup-lab")&&report.locatorsAfter==report.locatorsBefore&&LegacyResourcesAPI.ActiveCount==report.pendingBefore;Check(report.leasesCleaned,"Owned original default generic field/leases/locator/bundle retained");Save();}
 }
}
