using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using RoR2;
using UnityEngine;
using UnityEngine.Networking;

// Original automatic target selection; diagnostic aim, no interaction input or effect dispatch.
public sealed partial class MovementBatchProbe {
 [Serializable] public class InteractionSelectionReport {
  public bool slotCacheInitialized,itemLocked,pauseReady,cacheReady,selected,automatic,ungranted,conserved,selectionReleased,targetRemoved,cleaned;
  public byte[] slotEquipmentSet,inventoryEquipmentSet;public int equipmentBefore,equipmentAfter,inventoryEquipment,frames,fixedTicks;public uint targetId,moneyBefore,moneyAfter;public ulong xpBefore,xpAfter;
  public float seconds,range,cooldownSeconds;public string scope;
 }
 EquipmentDef[] InteractionSelectionEquipment(Result cfg){if(!cfg.originalInteractionSelection)return new EquipmentDef[0];var def=artifactBundle.LoadAsset<EquipmentDef>(cfg.recycleAsset);Check(def&&def.name=="Recycle"&&def.unlockableDef&&!def.requiredExpansion,"Original Recycle comparison contract changed");BindEnemyDefinition(typeof(RoR2Content.Equipment),"Recycle",def);return new[]{def};}
 static object DriverField(InteractionDriver driver,string name){return typeof(InteractionDriver).GetField(name,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(driver);}
 IEnumerator ProbeOriginalInteractionSelection(CharacterBody player,Result cfg){
  r.interactionSelection=new InteractionSelectionReport{scope="Original Unity InteractionDriver automatic source-barrel selection with actual local authority/source range, owned original unpaused PauseStopController and diagnostic aim. No interaction input/dispatch/reward effects/audio/physical binding, unlock/expansion grant, profile or startup acceptance."};r.phase="original-interaction-prepare";Save();
  Check(NetworkClient.active&&NetworkServer.active&&player.networkIdentity.hasAuthority&&player.networkIdentity.clientAuthorityOwner==activeBodyOwner&&!PauseStopController.instance,"Original owned client/pause context changed");
  var driver=player.GetComponent<InteractionDriver>();var bank=player.inputBank;Check(driver&&!driver.enabled&&!driver.currentInteractable&&!driver.interactableOverride&&!bank.interact.down&&!bank.interact.justPressed,"Original inactive interaction/input context changed");
  var requesters=(HashSet<UnityEngine.Object>)typeof(OutlineHighlight).GetField("preRenderHighlightRequesters",BindingFlags.Static|BindingFlags.NonPublic).GetValue(null);Check(!requesters.Contains(driver),"Original outline driver already registered");int requesterCount=requesters.Count;
  var priorAim=bank.aimDirection;float priorScale=Time.timeScale;GameObject pauseHost=null;PauseStopController pause=null;
  r.interactionSelection.moneyBefore=player.master.money;r.interactionSelection.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);
  try{
   r.interactionSelection.equipmentBefore=(int)player.equipmentSlot.equipmentIndex;r.interactionSelection.inventoryEquipment=(int)player.inventory.currentEquipmentIndex;Save();Check(player.inventory.currentEquipmentIndex==EquipmentIndex.None&&!player.equipmentSlot.enabled,"Original equipment must remain ungranted/disabled");if(!player.equipmentSlot.characterBody){Call(player.equipmentSlot,"Start");r.interactionSelection.slotCacheInitialized=true;}Call(player.equipmentSlot,"UpdateInventory");r.interactionSelection.equipmentAfter=(int)player.equipmentSlot.equipmentIndex;r.interactionSelection.slotEquipmentSet=player.equipmentSlot.activeEquipmentSet.ToArray();r.interactionSelection.inventoryEquipmentSet=player.inventory.activeEquipmentSet.ToArray();Check(player.equipmentSlot.characterBody==player&&player.equipmentSlot.activeEquipmentSet.Length==8&&player.equipmentSlot.activeEquipmentSet.Take(player.inventory.activeEquipmentSet.Length).SequenceEqual(player.inventory.activeEquipmentSet)&&player.equipmentSlot.activeEquipmentSet.Skip(player.inventory.activeEquipmentSet.Length).All(x=>x==0)&&player.equipmentSlot.equipmentIndex==EquipmentIndex.None&&!player.equipmentSlot.enabled,"Original equipment inventory cache mismatch");
   var comparison=DLC2Content.Items.LowerPricedChests;r.interactionSelection.itemLocked=comparison&&comparison.requiredExpansion&&player.inventory.GetItemCountPermanent(comparison)==0&&Run.instance.IsItemExpansionLocked(comparison.itemIndex);Save();Check(r.interactionSelection.itemLocked,"Original comparison item must remain ungranted/locked");r.interactionSelection.ungranted=comparison&&comparison.requiredExpansion&&player.inventory.GetItemCountPermanent(comparison)==0&&Run.instance.IsItemExpansionLocked(comparison.itemIndex)&&RoR2Content.Equipment.Recycle&&player.equipmentSlot.equipmentIndex==EquipmentIndex.None;Check(r.interactionSelection.ungranted,"Original comparison definitions must remain ungranted/locked");
   var report=new BarrelReport();var setup=PrepareOriginalBarrelClone(player,cfg,report);while(setup.MoveNext())yield return setup.Current;r.interactionSelection.targetId=report.netId;Check(report.sourceReady&&!barrelComponent.Networkopened,"Original unopened source target missing");
   pauseHost=new GameObject("Owned original interaction pause context");pauseHost.SetActive(false);pauseHost.AddComponent<NetworkIdentity>();pause=pauseHost.AddComponent<PauseStopController>();pauseHost.SetActive(true);yield return null;yield return null;Call(activeBodyClient,"Update");
   r.interactionSelection.pauseReady=PauseStopController.instance==pause&&!pause.isPaused&&pause.netId.Value!=0&&NetworkServer.FindLocalObject(pause.netId)==pauseHost&&Time.timeScale==priorScale;Check(r.interactionSelection.pauseReady,"Original unpaused controller lifecycle failed");
   if(DriverField(driver,"networkIdentity")==null)Call(driver,"Awake");r.interactionSelection.cacheReady=ReferenceEquals(DriverField(driver,"networkIdentity"),player.networkIdentity)&&ReferenceEquals(DriverField(driver,"inputBank"),bank)&&ReferenceEquals(DriverField(driver,"characterBody"),player)&&driver.interactor==player.GetComponent<Interactor>()&&ReferenceEquals(DriverField(driver,"equipmentSlot"),player.equipmentSlot);Check(r.interactionSelection.cacheReady,"Original driver component cache mismatch");
   r.interactionSelection.range=driver.interactor.maxInteractionDistance;Check(r.interactionSelection.range==3&&!driver.useAimOffset&&!driver.interactableOverride,"Original source driver query contract changed");var collider=barrelModel.GetComponentsInChildren<Collider>().First(x=>x.enabled);bank.aimDirection=(collider.bounds.center-bank.aimOrigin).normalized;driver.enabled=true;float began=Time.realtimeSinceStartup,cooldown=(float)DriverField(driver,"interactableCooldown");int fixedBegan=r.runClock.fixedTicks;
   while(Time.realtimeSinceStartup-began<3){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");if(driver.currentInteractable==barrelObject)break;}
   r.interactionSelection.selected=driver.currentInteractable==barrelObject&&requesters.Contains(driver);Check(r.interactionSelection.selected,"Original automatic driver did not select source barrel");r.phase="original-interaction-selected";Save();
   float hold=Time.realtimeSinceStartup;while(Time.realtimeSinceStartup-hold<3){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");r.interactionSelection.frames++;Check(driver.currentInteractable==barrelObject&&!driver.interactableOverride&&!bank.interact.down&&!bank.interact.justPressed&&!barrelComponent.Networkopened&&barrelMachine.state is EntityStates.Idle&&player.networkIdentity.hasAuthority&&PauseStopController.instance==pause&&!pause.isPaused,"Original automatic selection/input/authority changed");if(Time.frameCount%30==0)Save();}
   r.interactionSelection.seconds=Time.realtimeSinceStartup-began;r.interactionSelection.fixedTicks=r.runClock.fixedTicks-fixedBegan;r.interactionSelection.cooldownSeconds=cooldown-(float)DriverField(driver,"interactableCooldown");r.interactionSelection.automatic=r.interactionSelection.frames>50&&r.interactionSelection.fixedTicks>100&&Mathf.Abs(r.interactionSelection.cooldownSeconds-r.interactionSelection.fixedTicks*Time.fixedDeltaTime)<.05f;Check(r.interactionSelection.automatic,"Original automatic interaction callback intervals differ");
   // Withdraw only the owned target from physics before destroying its detached model/root.
   foreach(var ownedCollider in barrelObject.GetComponentsInChildren<Collider>(true).Concat(barrelModel.GetComponentsInChildren<Collider>(true)).Distinct())ownedCollider.enabled=false;Physics.SyncTransforms();float withdrawDeadline=Time.realtimeSinceStartup+2;while(driver.currentInteractable&&Time.realtimeSinceStartup<withdrawDeadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");}r.interactionSelection.selectionReleased=barrelObject&&!driver.currentInteractable&&!requesters.Contains(driver);Check(r.interactionSelection.selectionReleased,"Original driver did not release withdrawn live target");
   CleanupOriginalBarrel();yield return null;yield return null;Call(activeBodyClient,"Update");r.interactionSelection.targetRemoved=!barrelObject&&!barrelModel&&!barrelPreview&&!driver.currentInteractable;Check(r.interactionSelection.targetRemoved,"Original target destruction/selection removal incomplete");
   r.interactionSelection.moneyAfter=player.master.money;r.interactionSelection.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);r.interactionSelection.conserved=r.interactionSelection.moneyAfter==r.interactionSelection.moneyBefore&&r.interactionSelection.xpAfter==r.interactionSelection.xpBefore&&player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)==1&&player.inventory.GetItemCountPermanent(comparison)==0&&player.equipmentSlot.equipmentIndex==EquipmentIndex.None;Check(r.interactionSelection.conserved,"Target selection dispatched rewards or changed inventory");
  }finally{driver.enabled=false;bank.aimDirection=priorAim;CleanupOriginalBarrel();if(pauseHost){if(NetworkServer.active)NetworkServer.Destroy(pauseHost);else Destroy(pauseHost);}}
  yield return null;yield return null;Call(activeBodyClient,"Update");r.interactionSelection.cleaned=!pauseHost&&!pause&&!PauseStopController.instance&&!driver.enabled&&!driver.currentInteractable&&!requesters.Contains(driver)&&requesters.Count==requesterCount&&barrelMaterials.All(x=>!x)&&Time.timeScale==priorScale;Check(r.interactionSelection.cleaned,"Owned driver/pause/target/outline restoration failed");Save();
 }
}
