using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using RoR2;
using RoR2.Artifacts;
using RoR2.Projectile;
using UnityEngine;
using UnityEngine.Networking;

// Diagnostic factory arguments and read-only motion observations; source callbacks/native physics do the work.
public sealed partial class MovementBatchProbe {
 [Serializable] public class DropletFlightSample {public int ticks;public float seconds;public Vector3 position,velocity,serverPosition;public bool alive,authority;}
 [Serializable] public class PickupDropletFlightReport {
  public bool commandDisabled,catalogReady,noDisplay,factory,infoMatched,serverMapped,clientMapped,sourceCallbacks,authority,physicsMatched,networkAdvanced,noCollision,conserved,cleaned;
  public uint netId,moneyBefore,moneyAfter;public ulong xpBefore,xpAfter;public int pickup,ticks,instancesBefore,instancesAfter,pickupsBefore,pickupsAfter;public float seconds,velocityBound,positionBound;public Vector3 spawn,initialVelocity,displacement,velocity,angularVelocity,gravity,constantForce,expectedUndampedVelocity,expectedUndampedDisplacement;public DropletFlightSample[] samples;public string scope;
 }
 ArtifactDef[] DropletFlightArtifacts(Result cfg){if(!cfg.originalPickupDropletFlight)return new ArtifactDef[0];var def=artifactBundle.LoadAsset<ArtifactDef>(cfg.commandArtifactAsset);Check(def&&def.cachedName=="Command","Original source Command artifact missing");BindEnemyDefinition(typeof(RoR2Content.Artifacts),"Command",def);return new[]{def};}
 IEnumerator ProbeOriginalPickupDropletFlight(CharacterBody player,GameObject source){
  r.pickupDropletFlight=new PickupDropletFlightReport{scope="Original public source droplet factory, natural original Start/authority/network callbacks and native Rigidbody free-flight. Diagnostic placement100 units above actor/velocity; empty tier catalog naturally has no droplet display. No collision/pickup creation/chest Animator/ejection/grant/visual/audio/profile/full startup acceptance."};var report=r.pickupDropletFlight;r.phase="original-pickup-droplet-factory";Save();
  Check(r.pickupDropletLoad.callbackMatched&&ReferenceEquals(RewardField(typeof(PickupDropletController),"pickupDropletPrefab").GetValue(null),source)&&NetworkServer.active&&activeBodyClient.isConnected&&!ownsPickupCatalog&&PickupCatalog.pickupCount==0,"Accepted retained droplet source lease/catalog/client required");report.commandDisabled=RoR2Content.Artifacts.Command&&ArtifactCatalog.GetArtifactDef(RoR2Content.Artifacts.Command.artifactIndex)==RoR2Content.Artifacts.Command&&!CommandArtifactManager.IsCommandArtifactEnabled&&!CommandArtifactManager.commandCubePrefab;Check(report.commandDisabled,"Original Command comparison must remain disabled/ungranted");
  var flags=BindingFlags.Static|BindingFlags.NonPublic;foreach(var name in new[]{"entries","itemIndexToPickupIndex","equipmentIndexToPickupIndex","artifactIndexToPickupIndex","miscPickupIndexToPickupIndex","droneIndexToPickupIndex","<pickupCount>k__BackingField"}){var field=typeof(PickupCatalog).GetField(name,flags);Check(field!=null,"Original flight pickup field missing "+name);priorPickupFields[field]=field.GetValue(null);}pickupNameMap=(IDictionary)typeof(PickupCatalog).GetField("nameToPickupIndex",flags).GetValue(null);pickupTierMap=(IDictionary)typeof(PickupCatalog).GetField("itemTierToPickupIndex",flags).GetValue(null);Check(pickupNameMap.Count==0&&pickupTierMap.Count==0,"Unowned pickup maps");priorPickupAvailability=PickupCatalog.availability;ownsPickupCatalog=true;
  Func<PickupDropletController[]> droplets=()=>Resources.FindObjectsOfTypeAll<PickupDropletController>().Where(x=>x.gameObject.scene.IsValid()).ToArray();Func<int> pickups=()=>Resources.FindObjectsOfTypeAll<GenericPickupController>().Count(x=>x.gameObject.scene.IsValid());report.instancesBefore=droplets().Length;report.pickupsBefore=pickups();Check(report.instancesBefore==0&&report.pickupsBefore==0,"Unowned source droplet/pickup scene object present");report.moneyBefore=player.master.money;report.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);int syringe=player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe),lightning=player.inventory.GetItemCountPermanent(RoR2Content.Items.ChainLightning);GameObject owned=null;NetworkInstanceId id=default;var samples=new List<DropletFlightSample>();
  try{
   PickupCatalog.SetEntries(ItemCatalog.allItemDefs.Select(x=>x.CreatePickupDef()).ToArray());var index=PickupCatalog.FindPickupIndex(RoR2Content.Items.Syringe.itemIndex);var def=PickupCatalog.GetPickupDef(index);report.pickup=index.value;report.catalogReady=def!=null&&def.itemIndex==RoR2Content.Items.Syringe.itemIndex&&!RoR2Content.Items.Syringe.requiredExpansion&&!RoR2Content.Items.Syringe.unlockableDef&&!Run.instance.IsItemExpansionLocked(def.itemIndex);report.noDisplay=def!=null&&!def.dropletDisplayPrefab&&ItemTierCatalog.GetItemTierDef(ItemTier.Tier1)==null;Check(report.catalogReady&&report.noDisplay,"Original base/no-display diagnostic pickup domain changed");
   report.spawn=player.characterMotor.Motor.TransientPosition+Vector3.up*100;report.initialVelocity=new Vector3(0,20,2);report.gravity=Physics.gravity;Check(report.gravity==new Vector3(0,-30,0)&&Physics.OverlapSphere(report.spawn,.51f,~0,QueryTriggerInteraction.Ignore).Length==0,"Original gravity/high-altitude clear placement changed");var info=new GenericPickupController.CreatePickupInfo{pickup=new UniquePickup{pickupIndex=index},position=report.spawn,rotation=Quaternion.identity};int tickStart=r.runClock.fixedTicks;float fixedStart=Time.fixedTime;
   PickupDropletController.CreatePickupDroplet(info,report.spawn,report.initialVelocity);var created=droplets();Check(created.Length==1,"Original factory must create exactly one droplet");var droplet=created[0];owned=droplet.gameObject;var rigid=owned.GetComponent<Rigidbody>();var force=owned.GetComponent<ConstantForce>();var network=owned.GetComponent<ProjectileNetworkTransform>();var identity=owned.GetComponent<NetworkIdentity>();var collider=owned.GetComponent<SphereCollider>();Check(rigid&&force&&network&&identity&&collider,"Original factory component identity missing");id=identity.netId;report.netId=id.Value;report.constantForce=force.force;report.factory=owned.name==source.name+"(Clone)"&&droplet.pickupState==info.pickup&&rigid.velocity==report.initialVelocity&&Vector3.Distance(rigid.position,report.spawn)<.001f&&identity.isServer&&id.Value!=0&&collider.enabled&&!collider.isTrigger&&rigid.detectCollisions&&!rigid.isKinematic&&rigid.useGravity&&rigid.mass==1&&Mathf.Abs(rigid.drag-.1f)<.0001f&&force.enabled&&force.force==new Vector3(0,-15,0)&&network.enabled&&!network.checkForLocalPlayerAuthority;Check(report.factory,"Original factory source/state/network/initial velocity contract failed");
   var originalInfo=(GenericPickupController.CreatePickupInfo)typeof(PickupDropletController).GetField("createPickupInfo",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(droplet);report.infoMatched=originalInfo.pickup==info.pickup&&originalInfo.position==info.position&&originalInfo.rotation==info.rotation&&!originalInfo.prefabOverride&&!originalInfo.chest&&!originalInfo.duplicated&&!originalInfo.recycled&&originalInfo.artifactFlag==GenericPickupController.PickupArtifactFlag.NONE;Check(report.infoMatched,"Original factory retained info/Command flag differs");report.serverMapped=NetworkServer.FindLocalObject(id)==owned;Check(report.serverMapped,"Original droplet server registry missing");r.phase="original-pickup-droplet-flight";Save();
   float deadline=Time.realtimeSinceStartup+3;while(r.runClock.fixedTicks-tickStart<25&&Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");Check(owned&&droplet,"Original droplet disappeared before collision-free sample");var alive=(bool)typeof(PickupDropletController).GetField("alive",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(droplet);var authority=(bool)typeof(ProjectileNetworkTransform).GetField("hasEffectiveAuthority",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(network);samples.Add(new DropletFlightSample{ticks=r.runClock.fixedTicks-tickStart,seconds=Time.fixedTime-fixedStart,position=rigid.position,velocity=rigid.velocity,serverPosition=network.serverPosition,alive=alive,authority=authority});Check(alive&&pickups()==report.pickupsBefore&&force.enabled&&collider.enabled&&rigid.useGravity&&!rigid.isKinematic&&network.enabled,"Original flight collided/created pickup or changed source physics");report.samples=samples.ToArray();Save();}
   report.ticks=r.runClock.fixedTicks-tickStart;report.seconds=Time.fixedTime-fixedStart;Check(report.ticks>=25&&report.ticks<=30&&Mathf.Abs(report.seconds-report.ticks*Time.fixedDeltaTime)<.03f,"Original flight fixed interval/tick observations differ");report.clientMapped=ClientScene.FindLocalObject(id)==owned;report.sourceCallbacks=ReferenceEquals(typeof(ProjectileNetworkTransform).GetField("transform",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(network),owned.transform)&&ReferenceEquals(typeof(ProjectileNetworkTransform).GetField("rb",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(network),rigid);report.authority=(bool)typeof(ProjectileNetworkTransform).GetField("hasEffectiveAuthority",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(network);Check(report.clientMapped&&report.sourceCallbacks&&report.authority,"Original natural source Start/cache/authority/client mapping failed");
   report.displacement=rigid.position-report.spawn;report.velocity=rigid.velocity;report.angularVelocity=rigid.angularVelocity;float dt=Time.fixedDeltaTime,t=report.ticks*dt;var acceleration=report.gravity+report.constantForce/rigid.mass;report.expectedUndampedVelocity=report.initialVelocity+acceleration*t;report.expectedUndampedDisplacement=report.initialVelocity*t+acceleration*(dt*dt*report.ticks*(report.ticks+1)/2f);report.velocityBound=report.initialVelocity.magnitude*rigid.drag*t+.1f;report.positionBound=report.initialVelocity.magnitude*rigid.drag*t*t+.15f;float dampedForward=report.initialVelocity.z*Mathf.Pow(1-rigid.drag*dt,report.ticks);report.physicsMatched=Vector3.Distance(report.velocity,report.expectedUndampedVelocity)<report.velocityBound&&Vector3.Distance(report.displacement,report.expectedUndampedDisplacement)<report.positionBound&&Mathf.Abs(report.velocity.z-dampedForward)<.02f&&Mathf.Abs(report.displacement.x)<.01f&&report.displacement.y>3&&report.displacement.z>.8f&&report.velocity.y<0&&report.angularVelocity.sqrMagnitude>.0001f;Check(report.physicsMatched,"Original native droplet flight differs from source gravity/force/drag/tick bounds");report.networkAdvanced=network.serverPosition!=report.spawn&&Vector3.Distance(network.serverPosition,rigid.position)<rigid.velocity.magnitude*dt+.15f&&samples.Count(x=>x.serverPosition!=report.spawn)>2;Check(report.networkAdvanced,"Original automatic projectile network position did not follow native flight");report.noCollision=(bool)typeof(PickupDropletController).GetField("alive",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(droplet)&&droplets().Length==1&&pickups()==report.pickupsBefore;report.moneyAfter=player.master.money;report.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);report.conserved=report.moneyAfter==report.moneyBefore&&report.xpAfter==report.xpBefore&&syringe==player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)&&lightning==player.inventory.GetItemCountPermanent(RoR2Content.Items.ChainLightning);Check(report.noCollision&&report.conserved,"Original free-flight reached collision/grant or changed funds/inventory/XP");Save();
  }finally{if(owned)NetworkServer.Destroy(owned);CleanupOriginalItemPickup();}
  yield return null;yield return null;Call(activeBodyClient,"Update");report.instancesAfter=droplets().Length;report.pickupsAfter=pickups();report.cleaned=!owned&&!NetworkServer.FindLocalObject(id)&&!ClientScene.FindLocalObject(id)&&report.instancesAfter==report.instancesBefore&&report.pickupsAfter==report.pickupsBefore&&!ownsPickupCatalog&&PickupCatalog.pickupCount==0&&pickupNameMap.Count==0&&pickupTierMap.Count==0;Check(report.cleaned,"Owned original droplet server/client object or pickup catalog retained");Save();
 }
}
