using System;
using System.Collections;
using System.Linq;
using System.Reflection;
using RoR2;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.AddressableAssets;
using UnityEngine.AddressableAssets.ResourceLocators;
using UnityEngine.ResourceManagement.AsyncOperations;
using UnityEngine.ResourceManagement.ResourceLocations;
using UnityEngine.ResourceManagement.ResourceProviders;

// One untouched source asset and genuine startup callback; no droplet instantiation or motion.
public sealed partial class MovementBatchProbe {
 [Serializable] public class PickupDropletLoadReport {
  public bool syncLoaded,asyncMatched,sourceMatched,callbackMatched,pendingBalanced,noInstances,conserved,cleaned;
  public int components,instancesBefore,instancesAfter,pendingBefore,pendingAfter,referencesBeforeInit,referencesAfterInit,initCalls,locatorsBefore,locatorsAfter;
  public string[] componentTypes;public float mass,drag,angularDrag,radius;public Vector3 constantForce;public bool sourceGravity,sourceKinematic;public uint moneyBefore,moneyAfter;public ulong xpBefore,xpAfter;public string scope;
 }
 IEnumerator ProbeOriginalPickupDropletLoad(CharacterBody player,Result cfg){
  r.pickupDropletLoad=new PickupDropletLoadReport{scope="Original typed sync/async source PickupDroplet, genuine original Init callback/pending/refcount and source component/physics identity on Android. No instance/factory/animation/physics/grant/native audio/full startup acceptance."};var report=r.pickupDropletLoad;r.phase="original-pickup-droplet-load";Save();
  Check(r.chestPurchase.cleaned&&NetworkServer.active&&activeBodyClient.isConnected&&player.networkIdentity.hasAuthority,"Accepted source purchase/local-client context required");var field=RewardField(typeof(PickupDropletController),"pickupDropletPrefab");Check(field!=null&&field.GetValue(null)==null,"Existing original droplet prefab; refuse replacement");var prior=field.GetValue(null);report.pendingBefore=LegacyResourcesAPI.ActiveCount;report.locatorsBefore=Addressables.ResourceLocators.Count();Check(report.pendingBefore==0&&!AssetBundle.GetAllLoadedAssetBundles().Any(x=>x.name=="pickup-droplet-lab"),"Unowned droplet load/bundle present");
  Func<int> sceneInstances=()=>Resources.FindObjectsOfTypeAll<PickupDropletController>().Count(x=>x.gameObject.scene.IsValid());report.instancesBefore=sceneInstances();Check(report.instancesBefore==0,"Unowned droplet instance present");report.moneyBefore=player.master.money;report.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);int syringe=player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe),lightning=player.inventory.GetItemCountPermanent(RoR2Content.Items.ChainLightning);
  string key;Check(LegacyResourcesAPI.GetGuid("Prefabs/NetworkedObjects/PickupDroplet",out key)&&key==cfg.pickupDropletKey,"Original droplet legacy/catalog identity changed");var bundle=new ResourceLocationBase("pickup-droplet-lab",System.IO.Path.Combine(Application.persistentDataPath,"payload","pickup-droplet-lab"),typeof(AssetBundleProvider).FullName,typeof(IAssetBundleResource));bundle.Data=new AssetBundleRequestOptions{BundleName="pickup-droplet-lab"};var locator=new ResourceLocationMap("owned-pickup-droplet-load");locator.Add(key,new ResourceLocationBase(key,cfg.pickupDropletAsset,typeof(BundledAssetProvider).FullName,typeof(GameObject),bundle));Addressables.AddResourceLocator(locator);
  GameObject source=null;AsyncOperationHandle<GameObject> handle=default;bool ownsSync=false,ownsAsync=false,ownsInit=false;
  try{
   source=LegacyResourcesAPI.Load<GameObject>("Prefabs/NetworkedObjects/PickupDroplet");ownsSync=source;report.syncLoaded=source&&source.name=="PickupDroplet"&&!source.scene.IsValid();Check(report.syncLoaded,"Original sync droplet load failed");handle=LegacyResourcesAPI.LoadAsync<GameObject>("Prefabs/NetworkedObjects/PickupDroplet");ownsAsync=true;yield return handle;yield return null;report.asyncMatched=handle.Status==AsyncOperationStatus.Succeeded&&handle.Result==source;Check(report.asyncMatched,"Original async droplet identity differs");
   var components=source.GetComponents<Component>();report.components=components.Length;report.componentTypes=components.Select(x=>x?x.GetType().FullName:"MISSING").ToArray();var rigid=source.GetComponent<Rigidbody>();var collider=source.GetComponent<SphereCollider>();var force=source.GetComponent<ConstantForce>();Check(components.All(x=>x)&&components.Length==7&&source.GetComponent<PickupDropletController>()&&source.GetComponent<UnityEngine.Networking.NetworkIdentity>()&&source.GetComponent<RoR2.Projectile.ProjectileNetworkTransform>()&&rigid&&collider&&force,"Original droplet seven-component contract missing");report.mass=rigid.mass;report.drag=rigid.drag;report.angularDrag=rigid.angularDrag;report.radius=collider.radius;report.sourceGravity=rigid.useGravity;report.sourceKinematic=rigid.isKinematic;report.constantForce=force.force;report.sourceMatched=source.activeSelf&&source.layer==13&&Mathf.Abs(report.mass-1)<.0001f&&Mathf.Abs(report.drag-.1f)<.0001f&&Mathf.Abs(report.angularDrag-5)<.0001f&&report.sourceGravity&&!report.sourceKinematic&&Mathf.Abs(report.radius-.5f)<.0001f&&!collider.isTrigger&&force.enabled&&report.constantForce==new Vector3(0,-15,0)&&source.GetComponent<PickupDropletController>().pickupState==UniquePickup.none;Check(report.sourceMatched,"Original source droplet physics/state changed");
   Func<int> references=()=> (int)typeof(AsyncOperationHandle<GameObject>).GetProperty("ReferenceCount",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(handle);report.referencesBeforeInit=references();Check(report.referencesBeforeInit==2,"Original sync/async acquisition count differs");StaticCall(typeof(PickupDropletController),"Init");report.initCalls++;float deadline=Time.realtimeSinceStartup+8;while(field.GetValue(null)==null&&Time.realtimeSinceStartup<deadline)yield return null;yield return null;ownsInit=field.GetValue(null)!=null;report.referencesAfterInit=references();report.callbackMatched=ReferenceEquals(field.GetValue(null),source)&&report.initCalls==1&&report.referencesAfterInit==report.referencesBeforeInit+1;Check(report.callbackMatched,"Original Init callback/refcount did not resolve source droplet");report.pendingAfter=LegacyResourcesAPI.ActiveCount;report.pendingBalanced=report.pendingAfter==report.pendingBefore;report.instancesAfter=sceneInstances();report.noInstances=report.instancesAfter==report.instancesBefore;report.moneyAfter=player.master.money;report.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);report.conserved=report.moneyAfter==report.moneyBefore&&report.xpAfter==report.xpBefore&&syringe==player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)&&lightning==player.inventory.GetItemCountPermanent(RoR2Content.Items.ChainLightning);Check(report.pendingBalanced&&report.noInstances&&report.conserved,"Droplet load activated scene gameplay or changed funds/inventory/XP");Save();
   if(cfg.originalPickupDropletFlight){report.scope+=" Load-only assertions above precede a separate original flight segment; cleanup below follows its owned object removal.";var flight=ProbeOriginalPickupDropletFlight(player,source);while(flight.MoveNext())yield return flight.Current;}
  }finally{field.SetValue(null,prior);if(ownsInit&&source)Addressables.Release(source);if(ownsAsync&&handle.IsValid())Addressables.Release(handle);if(ownsSync&&source)Addressables.Release(source);Addressables.RemoveResourceLocator(locator);}
  yield return null;yield return null;report.locatorsAfter=Addressables.ResourceLocators.Count();report.cleaned=ReferenceEquals(field.GetValue(null),prior)&&!handle.IsValid()&&!AssetBundle.GetAllLoadedAssetBundles().Any(x=>x.name=="pickup-droplet-lab")&&report.locatorsAfter==report.locatorsBefore&&LegacyResourcesAPI.ActiveCount==report.pendingBefore&&sceneInstances()==report.instancesBefore;Check(report.cleaned,"Owned droplet field/reference/locator/bundle cleanup failed");Save();
 }
}
