using System;
using System.Collections;
using System.Linq;
using System.Reflection;
using RoR2;
using UnityEngine;
using UnityEngine.Networking;

public sealed class PickupDropletCollisionObservation : MonoBehaviour {
 public Action<Collision> observe;
 void OnCollisionEnter(Collision collision){observe?.Invoke(collision);}
}

// Native collisions call the original droplet/factory; this observer never dispatches them.
public sealed partial class MovementBatchProbe {
 [Serializable] public class PickupDropletCollisionReport {
  public bool groundMeasured,sourcePhysics,factory,infoMatched,collided,pickupCreated,dropletRemoved,earlyDisabled,available,conserved,cleaned,sourceName,pickupIdentity,originalFlags,displayOmitted,originalDelay,serverMapped,clientMapped,sourceConsumed,transformMatched;
  public int collisions,pickupIndex,ticks,instancesBefore,instancesAfter,pickupsBefore,pickupsAfter,contactLayer;public uint dropletId,pickupId,moneyBefore,moneyAfter;public ulong xpBefore,xpAfter;
  public float collisionSeconds,waitSeconds,positionError,rigidTransformOffset;public Vector3 spawn,initialVelocity,ground,contact,normal,collisionPosition,collisionTransformPosition,originalInfoPosition,pickupPosition;public string scope;
 }
 IEnumerator ProbeOriginalPickupDropletCollision(CharacterBody player,GameObject source,Result cfg){
  r.pickupDropletCollision=new PickupDropletCollisionReport{scope="Original droplet factory/native terrain collision/original generic factory/Start/delay. Diagnostic placement and public prefabOverride use the owned original GenericPickup with audio/display omitted as S146. No default generic Init, chest Animator/ejection, grant, pickup model/audio/physical interaction/full startup acceptance."};var report=r.pickupDropletCollision;r.phase="original-pickup-droplet-collision-prepare";Save();
  Check(r.pickupDropletFlight.cleaned&&r.pickupDropletLoad.callbackMatched&&ReferenceEquals(RewardField(typeof(PickupDropletController),"pickupDropletPrefab").GetValue(null),source)&&NetworkServer.active&&activeBodyClient.isConnected&&!ownsPickupCatalog&&PickupCatalog.pickupCount==0&&!pickupTemplates&&!pickupObject&&!RoR2.Artifacts.CommandArtifactManager.IsCommandArtifactEnabled,"Accepted flight/source/client and empty owned pickup context required");
  Func<PickupDropletController[]> droplets=()=>Resources.FindObjectsOfTypeAll<PickupDropletController>().Where(x=>x.gameObject.scene.IsValid()).ToArray();Func<GenericPickupController[]> pickups=()=>Resources.FindObjectsOfTypeAll<GenericPickupController>().Where(x=>x.gameObject.scene.IsValid()&&x.gameObject.activeInHierarchy).ToArray();report.instancesBefore=droplets().Length;report.pickupsBefore=pickups().Length;Check(report.instancesBefore==0&&report.pickupsBefore==0,"Unowned droplet/pickup present before collision probe");
  var flags=BindingFlags.Static|BindingFlags.NonPublic;foreach(var name in new[]{"entries","itemIndexToPickupIndex","equipmentIndexToPickupIndex","artifactIndexToPickupIndex","miscPickupIndexToPickupIndex","droneIndexToPickupIndex","<pickupCount>k__BackingField"}){var field=typeof(PickupCatalog).GetField(name,flags);Check(field!=null,"Original collision pickup field missing "+name);priorPickupFields[field]=field.GetValue(null);}pickupNameMap=(IDictionary)typeof(PickupCatalog).GetField("nameToPickupIndex",flags).GetValue(null);pickupTierMap=(IDictionary)typeof(PickupCatalog).GetField("itemTierToPickupIndex",flags).GetValue(null);Check(pickupNameMap.Count==0&&pickupTierMap.Count==0,"Unowned collision pickup maps");priorPickupAvailability=PickupCatalog.availability;ownsPickupCatalog=true;
  report.moneyBefore=player.master.money;report.xpBefore=TeamManager.instance.GetTeamExperience(TeamIndex.Player);int syringe=player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe),lightning=player.inventory.GetItemCountPermanent(RoR2Content.Items.ChainLightning);GameObject dropletObject=null;NetworkInstanceId dropletId=default,pickupId=default;
  try{
   PickupCatalog.SetEntries(ItemCatalog.allItemDefs.Select(x=>x.CreatePickupDef()).ToArray());var index=PickupCatalog.FindPickupIndex(RoR2Content.Items.Syringe.itemIndex);var def=PickupCatalog.GetPickupDef(index);report.pickupIndex=index.value;Check(def!=null&&def.itemIndex==RoR2Content.Items.Syringe.itemIndex&&!RoR2Content.Items.Syringe.requiredExpansion&&!RoR2Content.Items.Syringe.unlockableDef&&!Run.instance.IsItemExpansionLocked(def.itemIndex)&&!def.dropletDisplayPrefab,"Original allowed base/no-display collision domain changed");
   var genericSource=GenericPickupSource(cfg);Check(genericSource&&genericSource.name=="GenericPickup"&&genericSource.GetComponentsInChildren<Component>(true).All(x=>x),"Original generic source closure missing");pickupTemplates=new GameObject("Owned inactive collision pickup template");pickupTemplates.SetActive(false);pickupTemplate=Instantiate(genericSource,pickupTemplates.transform);pickupTemplate.name=genericSource.name;
   foreach(var component in pickupTemplate.GetComponentsInChildren<MonoBehaviour>(true)){if(component.GetType().Name.StartsWith("Ak",StringComparison.Ordinal)){DestroyImmediate(component);continue;}component.enabled=component is NetworkIdentity||component is GenericPickupController||component is EntityLocator;}
   var templateController=pickupTemplate.GetComponent<GenericPickupController>();Check(templateController&&templateController.waitDuration==.5f,"Original generic delay changed");if(templateController.pickupDisplay)templateController.pickupDisplay.gameObject.SetActive(false);templateController.pickupDisplay=null;pickupTemplate.SetActive(true);
   var actor=player.characterMotor.Motor.TransientPosition;RaycastHit ground=default;foreach(var offset in new[]{Vector3.right*8,Vector3.left*8,Vector3.forward*8,Vector3.back*8}){RaycastHit hit;if(!Physics.Raycast(actor+offset+Vector3.up*30,Vector3.down,out hit,100,LayerIndex.world.mask,QueryTriggerInteraction.Ignore)||hit.normal.y<.9f||hit.collider.gameObject.scene!=stageGeometryScene)continue;var candidate=hit.point+Vector3.up*3;if(Physics.OverlapSphere(candidate,.51f,~0,QueryTriggerInteraction.Ignore).Length!=0)continue;ground=hit;report.groundMeasured=true;report.ground=hit.point;report.spawn=candidate;break;}
   Check(report.groundMeasured&&!Physics.GetIgnoreLayerCollision(source.layer,LayerIndex.world.intVal)&&Physics.gravity==new Vector3(0,-30,0),"No measured clear original terrain/collision-layer/gravity candidate");report.initialVelocity=new Vector3(0,-2,0);var info=new GenericPickupController.CreatePickupInfo{prefabOverride=pickupTemplate,pickup=new UniquePickup{pickupIndex=index},position=report.spawn,rotation=Quaternion.identity};int startTicks=r.runClock.fixedTicks;float startFixed=Time.fixedTime;
   PickupDropletController.CreatePickupDroplet(info,report.spawn,report.initialVelocity);var spawned=droplets();Check(spawned.Length==1,"Original collision factory created wrong droplet count");var droplet=spawned[0];dropletObject=droplet.gameObject;var identity=dropletObject.GetComponent<NetworkIdentity>();dropletId=identity.netId;report.dropletId=dropletId.Value;var rigid=dropletObject.GetComponent<Rigidbody>();var collider=dropletObject.GetComponent<SphereCollider>();var force=dropletObject.GetComponent<ConstantForce>();report.sourcePhysics=rigid&&collider&&force&&rigid.useGravity&&!rigid.isKinematic&&rigid.detectCollisions&&rigid.mass==1&&Mathf.Abs(rigid.drag-.1f)<.0001f&&force.enabled&&force.force==new Vector3(0,-15,0)&&collider.enabled&&!collider.isTrigger&&Mathf.Abs(collider.radius-.5f)<.0001f;report.factory=identity.isServer&&dropletId.Value!=0&&NetworkServer.FindLocalObject(dropletId)==dropletObject&&droplet.pickupState==info.pickup&&rigid.velocity==report.initialVelocity;var retained=(GenericPickupController.CreatePickupInfo)typeof(PickupDropletController).GetField("createPickupInfo",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(droplet);report.infoMatched=retained.prefabOverride==pickupTemplate&&retained.pickup==info.pickup&&retained.artifactFlag==GenericPickupController.PickupArtifactFlag.NONE&&!retained.chest&&!retained.duplicated&&!retained.recycled;Check(report.sourcePhysics&&report.factory&&report.infoMatched,"Original droplet physics/factory/retained override changed");
   var observer=dropletObject.AddComponent<PickupDropletCollisionObservation>();observer.observe=collision=>{report.collisions++;if(report.collisions!=1)return;report.collisionSeconds=Time.fixedTime-startFixed;report.ticks=r.runClock.fixedTicks-startTicks;report.collisionPosition=rigid.position;report.collisionTransformPosition=dropletObject.transform.position;report.rigidTransformOffset=Vector3.Distance(report.collisionPosition,report.collisionTransformPosition);report.contactLayer=collision.collider.gameObject.layer;var contact=collision.GetContact(0);report.contact=contact.point;report.normal=contact.normal;report.collided=collision.collider.gameObject.scene==stageGeometryScene&&report.contactLayer==LayerIndex.world.intVal&&Vector3.Distance(contact.point,report.ground)<1;};r.phase="original-pickup-droplet-collision";Save();
   float deadline=Time.realtimeSinceStartup+3;while(pickups().Length==0&&Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");Save();}var created=pickups();Check(created.Length==1&&report.collided&&report.collisions>=1&&report.collisionSeconds>0&&report.collisionSeconds<1,"Native original terrain collision did not create exactly one pickup");ownedPickup=created[0];pickupObject=ownedPickup.gameObject;pickupId=pickupObject.GetComponent<NetworkIdentity>().netId;report.pickupId=pickupId.Value;report.pickupPosition=pickupObject.transform.position;var collisionInfo=(GenericPickupController.CreatePickupInfo)typeof(PickupDropletController).GetField("createPickupInfo",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(droplet);report.originalInfoPosition=collisionInfo.position;report.sourceConsumed=!(bool)typeof(PickupDropletController).GetField("alive",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(droplet);report.positionError=Vector3.Distance(report.pickupPosition,report.originalInfoPosition);report.transformMatched=Vector3.Distance(report.originalInfoPosition,report.collisionTransformPosition)<.001f;report.sourceName=pickupObject.name==pickupTemplate.name+"(Clone)";report.pickupIdentity=ownedPickup.pickup==info.pickup;report.originalFlags=!ownedPickup.Duplicated&&!ownedPickup.Recycled&&!ownedPickup.chestGeneratedFrom;report.displayOmitted=!ownedPickup.pickupDisplay;report.originalDelay=ownedPickup.waitDuration==.5f;report.serverMapped=pickupId.Value!=0&&NetworkServer.FindLocalObject(pickupId)==pickupObject;report.clientMapped=ClientScene.FindLocalObject(pickupId)==pickupObject;report.pickupCreated=report.sourceName&&report.pickupIdentity&&report.originalFlags&&report.displayOmitted&&report.originalDelay&&report.serverMapped&&report.clientMapped&&report.sourceConsumed&&report.transformMatched&&report.positionError<.001f&&Vector3.Distance(report.pickupPosition,report.spawn)>.5f;Save();Check(report.pickupCreated,"Original collision position/state/factory/network mapping changed");
   yield return null;Call(activeBodyClient,"Update");report.dropletRemoved=!dropletObject&&!NetworkServer.FindLocalObject(dropletId)&&!ClientScene.FindLocalObject(dropletId)&&droplets().Length==0;Check(report.dropletRemoved,"Original collision destruction retained droplet/server/client mapping");var interactor=player.GetComponent<Interactor>();var waitStart=(Run.FixedTimeStamp)typeof(GenericPickupController).GetField("waitStartTime",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(ownedPickup);report.earlyDisabled=ownedPickup.GetInteractability(interactor)==Interactability.Disabled&&waitStart.timeSince<.5f;Check(report.earlyDisabled,"Original pickup Start/initial half-second delay missing");r.phase="original-collision-pickup-wait";Save();
   deadline=Time.realtimeSinceStartup+2;while(waitStart.timeSince<.5f&&Time.realtimeSinceStartup<deadline){yield return new WaitForEndOfFrame();Call(activeBodyClient,"Update");Check(pickupObject&&pickups().Length==1&&droplets().Length==0&&player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)==syringe,"Original collision pickup duplicated/disappeared/granted during delay");}report.waitSeconds=waitStart.timeSince;report.available=ownedPickup.GetInteractability(interactor)==Interactability.Available&&report.waitSeconds>=.5f&&report.waitSeconds<.7f;Check(report.available,"Original collision pickup delay/permission did not become available");report.moneyAfter=player.master.money;report.xpAfter=TeamManager.instance.GetTeamExperience(TeamIndex.Player);report.conserved=report.moneyAfter==report.moneyBefore&&report.xpAfter==report.xpBefore&&player.inventory.GetItemCountPermanent(RoR2Content.Items.Syringe)==syringe&&player.inventory.GetItemCountPermanent(RoR2Content.Items.ChainLightning)==lightning;Check(report.conserved,"Collision/create/delay changed funds/inventory/XP");Save();
  }finally{if(dropletObject)NetworkServer.Destroy(dropletObject);CleanupOriginalItemPickup();}
  yield return null;yield return null;Call(activeBodyClient,"Update");report.instancesAfter=droplets().Length;report.pickupsAfter=pickups().Length;report.cleaned=!dropletObject&&!pickupObject&&!pickupTemplate&&!pickupTemplates&&!NetworkServer.FindLocalObject(dropletId)&&!ClientScene.FindLocalObject(dropletId)&&!NetworkServer.FindLocalObject(pickupId)&&!ClientScene.FindLocalObject(pickupId)&&report.instancesAfter==report.instancesBefore&&report.pickupsAfter==report.pickupsBefore&&!ownsPickupCatalog&&PickupCatalog.pickupCount==0&&pickupNameMap.Count==0&&pickupTierMap.Count==0;Check(report.cleaned,"Owned collision droplet/pickup/template/catalog/map cleanup incomplete");Save();
 }
}
